//! Atlas syntax front-end.
//!
//! The grammar is generated by LALRPOP, while the adapter below translates
//! the stateful Atlas lexer into the parser's spanned-token stream. Keeping
//! this adapter separate means the lexer can grow its context-sensitive token
//! rules without leaking them into grammar actions.

use std::fmt;

use num_bigint::BigInt;

use crate::{
    diagnostic::{Diagnostic, ErrorKind, SourceSpan},
    formula::{
        end_formula, extend_formula, start_formula, start_unary_formula, FormulaOperator,
        FormulaStack, FormulaTree,
    },
    lex::{tokenize, Token, TokenKind},
    source::SourceText,
};

lalrpop_util::lalrpop_mod!(grammar);

/// A syntax tree for the expression slice currently covered by the parser.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Expr {
    Integer {
        value: BigInt,
        span: SourceSpan,
    },
    Boolean {
        value: bool,
        span: SourceSpan,
    },
    String {
        value: String,
        span: SourceSpan,
    },
    Identifier {
        name: String,
        span: SourceSpan,
    },
    Assignment {
        name: String,
        target_span: SourceSpan,
        value: Box<Expr>,
        span: SourceSpan,
    },
    Unary {
        op: UnaryOp,
        operand: Box<Expr>,
        span: SourceSpan,
    },
    Binary {
        op: BinaryOp,
        lhs: Box<Expr>,
        rhs: Box<Expr>,
        span: SourceSpan,
    },
    OperatorCall {
        operator: FormulaOperator,
        arguments: Vec<Expr>,
        span: SourceSpan,
    },
    Group {
        inner: Box<Expr>,
        span: SourceSpan,
    },
}

impl Expr {
    pub fn span(&self) -> SourceSpan {
        match self {
            Self::Integer { span, .. }
            | Self::Boolean { span, .. }
            | Self::String { span, .. }
            | Self::Identifier { span, .. }
            | Self::Assignment { span, .. }
            | Self::Unary { span, .. }
            | Self::Binary { span, .. }
            | Self::OperatorCall { span, .. }
            | Self::Group { span, .. } => *span,
        }
    }
}

/// A top-level Atlas command.
///
/// Global definitions use command syntax and produce definition output;
/// assignments remain expressions and return their assigned value.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Command {
    Expression(Expr),
    Define {
        name: String,
        name_span: SourceSpan,
        value: Expr,
        span: SourceSpan,
    },
}

impl Command {
    pub fn span(&self) -> SourceSpan {
        match self {
            Self::Expression(expression) => expression.span(),
            Self::Define { span, .. } => *span,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnaryOp {
    Not,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BinaryOp {
    And,
    Or,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Program {
    pub expressions: Vec<Expr>,
}

/// Public parser error. The diagnostic category remains the compatibility
/// boundary; wording can be refined after Atlas oracle comparisons.
pub type ParseError = Diagnostic;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpannedValue<T> {
    pub value: T,
    pub span: SourceSpan,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ParserToken {
    Integer(SpannedValue<BigInt>),
    Boolean(SpannedValue<bool>),
    String(SpannedValue<String>),
    Identifier(SpannedValue<String>),
    Operator(SpannedValue<FormulaOperator>),
    Becomes(SourceSpan),
    Colon(SourceSpan),
    And(SourceSpan),
    Or(SourceSpan),
    Not(SourceSpan),
    LParen(SourceSpan),
    RParen(SourceSpan),
    Newline(SourceSpan),
    Unsupported(SpannedValue<String>),
}

impl ParserToken {
    fn span(&self) -> SourceSpan {
        match self {
            Self::Integer(value) => value.span,
            Self::Boolean(value) => value.span,
            Self::String(value) => value.span,
            Self::Identifier(value) => value.span,
            Self::Operator(value) => value.span,
            Self::Unsupported(value) => value.span,
            Self::Becomes(span)
            | Self::Colon(span)
            | Self::And(span)
            | Self::Or(span)
            | Self::Not(span)
            | Self::LParen(span)
            | Self::RParen(span)
            | Self::Newline(span) => *span,
        }
    }
}

impl fmt::Display for ParserToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Integer(_) => "integer",
            Self::Boolean(_) => "boolean",
            Self::String(_) => "string",
            Self::Identifier(_) => "identifier",
            Self::Operator(operator) => operator.value.symbol.as_str(),
            Self::Becomes(_) => ":=",
            Self::Colon(_) => ":",
            Self::And(_) => "and",
            Self::Or(_) => "or",
            Self::Not(_) => "not",
            Self::LParen(_) => "(",
            Self::RParen(_) => ")",
            Self::Newline(_) => "newline",
            Self::Unsupported(_) => "unsupported token",
        })
    }
}

type Spanned<T> = Result<(usize, T, usize), ()>;

struct TokenStream {
    tokens: std::vec::IntoIter<(ParserToken, SourceSpan)>,
    index: usize,
}

impl TokenStream {
    fn new(tokens: Vec<(ParserToken, SourceSpan)>) -> Self {
        Self {
            tokens: tokens.into_iter(),
            index: 0,
        }
    }
}

impl Iterator for TokenStream {
    type Item = Spanned<ParserToken>;

    fn next(&mut self) -> Option<Self::Item> {
        let (token, _) = self.tokens.next()?;
        let start = self.index;
        self.index += 1;
        Some(Ok((start, token, self.index)))
    }
}

fn parser_tokens_from_tokens(
    tokens: impl IntoIterator<Item = Token>,
) -> Result<Vec<(ParserToken, SourceSpan)>, ParseError> {
    tokens
        .into_iter()
        .filter_map(|token| {
            let span = token.span;
            match token.kind {
                TokenKind::Eof => None,
                TokenKind::Integer => match token.lexeme.parse::<BigInt>() {
                    Ok(value) => Some(Ok((
                        ParserToken::Integer(SpannedValue { value, span }),
                        span,
                    ))),
                    Err(_) => Some(Err(Diagnostic::new(
                        ErrorKind::Lexical,
                        "invalid integer",
                        Some(span),
                    ))),
                },
                TokenKind::String => Some(Ok((
                    ParserToken::String(SpannedValue {
                        value: token.value.unwrap_or_default(),
                        span,
                    }),
                    span,
                ))),
                TokenKind::Identifier => Some(Ok((
                    ParserToken::Identifier(SpannedValue {
                        value: token.lexeme,
                        span,
                    }),
                    span,
                ))),
                TokenKind::Keyword(word) => {
                    let token = match word.as_str() {
                        "true" => ParserToken::Boolean(SpannedValue { value: true, span }),
                        "false" => ParserToken::Boolean(SpannedValue { value: false, span }),
                        "and" => ParserToken::And(span),
                        "or" => ParserToken::Or(span),
                        "not" => ParserToken::Not(span),
                        _ => ParserToken::Unsupported(SpannedValue { value: word, span }),
                    };
                    Some(Ok((token, span)))
                }
                TokenKind::Operator(operator) => {
                    let token = if operator == ":=" {
                        ParserToken::Becomes(span)
                    } else {
                        parser_operator(operator, span).unwrap_or_else(|operator| {
                            ParserToken::Unsupported(SpannedValue {
                                value: operator,
                                span,
                            })
                        })
                    };
                    Some(Ok((token, span)))
                }
                TokenKind::Punctuation(punctuation) => {
                    let token = match punctuation {
                        '(' => ParserToken::LParen(span),
                        ')' => ParserToken::RParen(span),
                        ':' => ParserToken::Colon(span),
                        '~' => parser_operator("~".to_owned(), span)
                            .expect("tilde has a fixed Atlas priority"),
                        _ => ParserToken::Unsupported(SpannedValue {
                            value: punctuation.to_string(),
                            span,
                        }),
                    };
                    Some(Ok((token, span)))
                }
                TokenKind::Unsupported(value) => Some(Ok((
                    ParserToken::Unsupported(SpannedValue { value, span }),
                    span,
                ))),
                TokenKind::Newline => Some(Ok((ParserToken::Newline(span), span))),
            }
        })
        .collect()
}

fn parser_operator(symbol: String, span: SourceSpan) -> Result<ParserToken, String> {
    let priority = match symbol.as_str() {
        "<" | "<=" | ">" | ">=" | "=" | "!=" => 2,
        "+" | "-" => 4,
        "*" | "%" | "/" | "&" | "\\" | "\\%" => 6,
        "^" => 7,
        "#" | "##" | "~" => 8,
        _ => return Err(symbol),
    };
    let value = FormulaOperator::new(symbol, priority).with_span(span);
    Ok(ParserToken::Operator(SpannedValue { value, span }))
}

fn parser_tokens(source: &SourceText) -> Result<Vec<(ParserToken, SourceSpan)>, ParseError> {
    let tokens = tokenize(source).map_err(|mut errors| errors.remove(0))?;
    parser_tokens_from_tokens(tokens)
}

/// Parse an Atlas source buffer into the current expression-level AST.
pub fn parse(source: &SourceText) -> Result<Program, ParseError> {
    let tokens = parser_tokens(source)?;
    let spans: Vec<SourceSpan> = tokens.iter().map(|(_, span)| *span).collect();
    grammar::ProgramParser::new()
        .parse(TokenStream::new(tokens))
        .map_err(|error| syntax_error(error, source, &spans))
}

/// Parse one already-delimited Atlas command. The lexer remains responsible
/// for command boundaries; this adapter deliberately does not tokenize the
/// rest of the source, so session state can change before the next command.
pub fn parse_command(tokens: &[Token], source: &SourceText) -> Result<Command, ParseError> {
    let parsed = parser_tokens_from_tokens(tokens.iter().cloned())?;
    let spans: Vec<SourceSpan> = parsed.iter().map(|(_, span)| *span).collect();
    grammar::CommandParser::new()
        .parse(TokenStream::new(parsed))
        .map_err(|error| syntax_error(error, source, &spans))
}

fn syntax_error(
    error: lalrpop_util::ParseError<usize, ParserToken, ()>,
    source: &SourceText,
    spans: &[SourceSpan],
) -> ParseError {
    let (message, span) = match error {
        lalrpop_util::ParseError::InvalidToken { location } => (
            "invalid token",
            spans
                .get(location)
                .copied()
                .or_else(|| Some(source.span(source.as_str().len(), source.as_str().len()))),
        ),
        lalrpop_util::ParseError::UnrecognizedEof { location, .. } => (
            "unexpected end of input",
            spans
                .get(location)
                .copied()
                .or_else(|| Some(source.span(source.as_str().len(), source.as_str().len()))),
        ),
        lalrpop_util::ParseError::UnrecognizedToken {
            token: (start, token, _),
            ..
        }
        | lalrpop_util::ParseError::ExtraToken {
            token: (start, token, _),
        } => (
            "unexpected token",
            spans.get(start).copied().or_else(|| Some(token.span())),
        ),
        lalrpop_util::ParseError::User { .. } => ("parser input error", None),
    };
    Diagnostic::new(ErrorKind::Syntax, message, span)
}

fn join_span(start: SourceSpan, end: SourceSpan) -> SourceSpan {
    debug_assert_eq!(start.source_id(), end.source_id());
    SourceSpan::new(
        start.source_id(),
        start.byte_start(),
        end.byte_end(),
        start.start,
        end.end,
    )
}

fn unary(op: UnaryOp, operand: Expr, operator: SourceSpan) -> Expr {
    Expr::Unary {
        op,
        span: join_span(operator, operand.span()),
        operand: Box::new(operand),
    }
}

fn binary(op: BinaryOp, lhs: Expr, rhs: Expr) -> Expr {
    let span = join_span(lhs.span(), rhs.span());
    Expr::Binary {
        op,
        span,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    }
}

fn assignment(target: SpannedValue<String>, value: Expr) -> Expr {
    Expr::Assignment {
        name: target.value,
        target_span: target.span,
        span: join_span(target.span, value.span()),
        value: Box::new(value),
    }
}

fn definition(target: SpannedValue<String>, value: Expr) -> Command {
    Command::Define {
        name: target.value,
        name_span: target.span,
        span: join_span(target.span, value.span()),
        value,
    }
}

fn start_binary_formula(lhs: Expr, operator: FormulaOperator) -> FormulaStack<Expr> {
    start_formula(lhs, operator)
}

fn start_prefix_formula(operator: FormulaOperator) -> FormulaStack<Expr> {
    start_unary_formula(operator)
}

fn extend_operator_formula(
    stack: FormulaStack<Expr>,
    operand: Expr,
    operator: FormulaOperator,
) -> FormulaStack<Expr> {
    extend_formula(stack, operand, operator)
}

fn finish_operator_formula(stack: FormulaStack<Expr>, operand: Expr) -> Expr {
    expression_from_formula(end_formula(stack, operand))
}

fn prefix_operator_call(operator: FormulaOperator, operand: Expr) -> Expr {
    operator_call(operator, vec![operand])
}

fn expression_from_formula(tree: FormulaTree<Expr>) -> Expr {
    match tree {
        FormulaTree::Operand(expression) => expression,
        FormulaTree::Unary { operator, operand } => {
            let operand = expression_from_formula(*operand);
            operator_call(operator, vec![operand])
        }
        FormulaTree::Binary {
            operator,
            left,
            right,
        } => {
            let left = expression_from_formula(*left);
            let right = expression_from_formula(*right);
            operator_call(operator, vec![left, right])
        }
    }
}

fn operator_call(operator: FormulaOperator, arguments: Vec<Expr>) -> Expr {
    debug_assert!(matches!(arguments.len(), 1 | 2));
    let span = match arguments.as_slice() {
        [operand] => operator
            .span
            .map(|operator_span| join_span(operator_span, operand.span()))
            .unwrap_or_else(|| operand.span()),
        [left, right] => join_span(left.span(), right.span()),
        _ => unreachable!("Atlas formula operators have arity one or two"),
    };
    Expr::OperatorCall {
        operator,
        arguments,
        span,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use num_bigint::BigInt;

    fn expression_shape(expression: &Expr) -> String {
        match expression {
            Expr::Integer { value, .. } => value.to_string(),
            Expr::Boolean { value, .. } => value.to_string(),
            Expr::String { value, .. } => format!("\"{value}\""),
            Expr::Identifier { name, .. } => name.clone(),
            Expr::Assignment { name, value, .. } => {
                format!("assign({name},{})", expression_shape(value))
            }
            Expr::Unary {
                op: UnaryOp::Not,
                operand,
                ..
            } => {
                format!("not({})", expression_shape(operand))
            }
            Expr::Binary {
                op: BinaryOp::And,
                lhs,
                rhs,
                ..
            } => format!("and({},{})", expression_shape(lhs), expression_shape(rhs)),
            Expr::Binary {
                op: BinaryOp::Or,
                lhs,
                rhs,
                ..
            } => format!("or({},{})", expression_shape(lhs), expression_shape(rhs)),
            Expr::OperatorCall {
                operator,
                arguments,
                ..
            } => format!(
                "{}@{}({})",
                operator.symbol,
                operator.priority,
                arguments
                    .iter()
                    .map(expression_shape)
                    .collect::<Vec<_>>()
                    .join(",")
            ),
            Expr::Group { inner, .. } => format!("group({})", expression_shape(inner)),
        }
    }

    fn parse_one(source: &str) -> Expr {
        let mut expressions = parse(&SourceText::new(source))
            .expect("formula parses")
            .expressions;
        assert_eq!(expressions.len(), 1);
        expressions.remove(0)
    }

    #[test]
    fn parses_assignment_as_a_right_associative_expression() {
        let expression = parse_one("x := y := 1");
        assert_eq!(expression_shape(&expression), "assign(x,assign(y,1))");
    }

    #[test]
    fn parses_fixture_program_and_preserves_precedence() {
        let source = SourceText::new(include_str!("../../../tests/fixtures/parse/basic.atlas"));
        let program = parse(&source).expect("fixture parses");
        assert_eq!(program.expressions.len(), 6);
        assert!(
            matches!(program.expressions[0], Expr::Integer { ref value, .. } if value == &BigInt::from(42))
        );
        assert!(matches!(
            program.expressions[1],
            Expr::Boolean { value: true, .. }
        ));
        assert!(
            matches!(program.expressions[2], Expr::String { ref value, .. } if value == "atlas")
        );
        assert_eq!(
            expression_shape(&program.expressions[4]),
            "-@4(*@6(group(+@4(1,2)),3),/@6(4,2))"
        );
        assert!(matches!(
            program.expressions[5],
            Expr::Binary {
                op: BinaryOp::Or,
                ..
            }
        ));
    }

    #[test]
    fn rejects_trailing_expression_token() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/parse/negative_trailing_token.atlas"
        ));
        let error = parse(&source).expect_err("two adjacent expressions are invalid");
        assert_eq!(error.kind, ErrorKind::Syntax);
    }

    #[test]
    fn parses_integer_literals_without_a_machine_word_limit() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/parse/exact_numerics.atlas"
        ));
        let program = parse(&source).expect("arbitrary-precision integer fixture parses");
        assert!(matches!(
            &program.expressions[0],
            Expr::Integer { value, .. }
                if value.to_string() == "1234567890123456789012345678901234567890"
        ));
    }

    #[test]
    fn parses_unary_minus_for_integer_and_grouped_expression() {
        let source = SourceText::new("-123\n-(1 / 2)");
        let program = parse(&source).expect("unary minus source parses");
        assert_eq!(expression_shape(&program.expressions[0]), "-@4(123)");
        assert_eq!(
            expression_shape(&program.expressions[1]),
            "-@4(group(/@6(1,2)))"
        );
    }

    #[test]
    fn reduces_symbolic_formulae_with_atlas_associativity_and_unary_rules() {
        assert_eq!(expression_shape(&parse_one("a-b-c")), "-@4(-@4(a,b),c)");
        assert_eq!(expression_shape(&parse_one("a^b^c")), "^@7(a,^@7(b,c))");
        assert_eq!(expression_shape(&parse_one("-x^2")), "-@4(^@7(x,2))");
        assert_eq!(
            expression_shape(&parse_one("x^-2*y")),
            "*@6(^@7(x,-@4(2)),y)"
        );
    }

    #[test]
    fn maps_symbolic_tokens_to_oracle_priorities() {
        let cases = [
            ("<", 2),
            ("<=", 2),
            (">", 2),
            (">=", 2),
            ("=", 2),
            ("!=", 2),
            ("+", 4),
            ("-", 4),
            ("*", 6),
            ("%", 6),
            ("/", 6),
            ("&", 6),
            ("\\", 6),
            ("\\%", 6),
            ("^", 7),
            ("#", 8),
            ("##", 8),
            ("~", 8),
        ];

        for (symbol, priority) in cases {
            let expression = parse_one(&format!("a{symbol}b"));
            match expression {
                Expr::OperatorCall {
                    operator,
                    arguments,
                    ..
                } => {
                    assert_eq!(operator.symbol, symbol);
                    assert_eq!(operator.priority, priority);
                    assert_eq!(arguments.len(), 2);
                    assert!(operator.span.is_some());
                }
                other => panic!("expected operator call for {symbol}, got {other:?}"),
            }
        }
    }
}
