//! Atlas syntax front-end.
//!
//! The grammar is generated by LALRPOP, while the adapter below translates
//! the stateful Atlas lexer into the parser's spanned-token stream. Keeping
//! this adapter separate means the lexer can grow its context-sensitive token
//! rules without leaking them into grammar actions.

use std::fmt;

use malachite::Integer as BigInt;

use crate::{
    diagnostic::{Diagnostic, ErrorKind, SourceSpan},
    formula::{
        end_formula, extend_formula, start_formula, start_unary_formula, FormulaOperator,
        FormulaStack, FormulaTree,
    },
    lex::{tokenize, Token, TokenKind},
    source::SourceText,
};

lalrpop_util::lalrpop_mod!(
    #[allow(clippy::result_large_err)]
    // The generated symbol enum size tracks the AST; boxing decisions in
    // generated code are LALRPOP's, not ours.
    #[allow(clippy::large_enum_variant)]
    grammar
);

/// A syntax tree for the expression slice currently covered by the parser.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Expr {
    Integer {
        value: BigInt,
        span: SourceSpan,
    },
    Boolean {
        value: bool,
        span: SourceSpan,
    },
    String {
        value: String,
        span: SourceSpan,
    },
    Tuple {
        elements: Vec<Expr>,
        span: SourceSpan,
    },
    List {
        elements: Vec<Expr>,
        span: SourceSpan,
    },
    Subscription {
        array: Box<Expr>,
        index: Box<Expr>,
        reversed: bool,
        span: SourceSpan,
    },
    Slice {
        array: Box<Expr>,
        lower: Box<Expr>,
        upper: Box<Expr>,
        flags: SliceFlags,
        span: SourceSpan,
    },
    Identifier {
        name: String,
        span: SourceSpan,
    },
    Assignment {
        name: String,
        target_span: SourceSpan,
        value: Box<Expr>,
        span: SourceSpan,
    },
    Let {
        binding_groups: Vec<Vec<LetBinding>>,
        body: Box<Expr>,
        span: SourceSpan,
    },
    Unary {
        op: UnaryOp,
        operand: Box<Expr>,
        span: SourceSpan,
    },
    Binary {
        op: BinaryOp,
        lhs: Box<Expr>,
        rhs: Box<Expr>,
        span: SourceSpan,
    },
    OperatorCall {
        operator: FormulaOperator,
        arguments: Vec<Expr>,
        span: SourceSpan,
    },
    Call {
        callee: Box<Expr>,
        arguments: Vec<Expr>,
        span: SourceSpan,
    },
    /// A non-recursive function literal. Parameter patterns beyond a simple
    /// typed name are intentionally deferred to the later pattern slice.
    Lambda {
        parameters: Vec<LambdaParam>,
        body: Box<Expr>,
        span: SourceSpan,
    },
    /// `return value`, intercepted by a function-call boundary during eval.
    Return {
        value: Box<Expr>,
        span: SourceSpan,
    },
    /// A recursive function literal `rec_fun name(params) result: body`
    /// (parser.y:231). The declared result type is the body's context
    /// type, and `name` is bound to the closure itself inside the body.
    RecLambda {
        self_name: String,
        self_span: SourceSpan,
        parameters: Vec<LambdaParam>,
        // Boxed to keep `Expr` small (and downstream enums under clippy's
        // `large_enum_variant` threshold).
        result_type: Box<TypeExpr>,
        body: Box<Expr>,
        span: SourceSpan,
    },
    Group {
        inner: Box<Expr>,
        span: SourceSpan,
    },
    /// `if c then t [else e] fi` (elif desugars to nesting at parse;
    /// a missing else branch is the void value, parser.y:415).
    Conditional {
        condition: Box<Expr>,
        then_branch: Box<Expr>,
        else_branch: Box<Expr>,
        span: SourceSpan,
    },
    /// `type: expr` — context-typing per upstream `make_cast` (parser.y:240).
    Cast {
        target: TypeExpr,
        body: Box<Expr>,
        span: SourceSpan,
    },
    /// `first; second` sequencing (parser.y:243): the first expression
    /// evaluates for effects against a void context; the sequence yields
    /// the second expression's value.
    Sequence {
        first: Box<Expr>,
        second: Box<Expr>,
        span: SourceSpan,
    },
    /// `while condition do body od` (parser.y:364): each iteration's body
    /// value is collected into a row; a missing condition (`while do …`)
    /// is the constant true (parser.y:443).
    While {
        condition: Option<Box<Expr>>,
        body: Box<Expr>,
        span: SourceSpan,
    },
    /// `for pattern[@index] in row do body od` (parser.y:506-531). Boxed
    /// to keep `Expr` small, like `RecLambda`.
    For(Box<ForLoop>),
    /// `break` (parser.y BREAK unit): unwinds to the innermost loop, whose
    /// breaking iteration contributes no value to the collected row.
    Break {
        span: SourceSpan,
    },
    /// `case subject | tag[(pattern)]: body … [else body] esac`
    /// (parser.y:480-482 discrimination). Boxed to keep `Expr` small.
    Case(Box<CaseExpr>),
}

/// A case discrimination: the subject (a tabled union value) and its
/// branches in source order.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CaseExpr {
    pub subject: Expr,
    pub branches: Vec<CaseBranch>,
    pub span: SourceSpan,
}

/// The payload of a `for` loop: the element pattern (absent for the
/// throw-away form), the optional `@`-bound 0-based index name, the row
/// iterated over, and the body evaluated once per element.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ForLoop {
    pub pattern: Option<Pattern>,
    pub index: Option<SpannedValue<String>>,
    pub iterable: Box<Expr>,
    pub body: Box<Expr>,
    pub span: SourceSpan,
}

/// A binding pattern (parser.y:708-749): `x`, const `!x`, tuple
/// destructuring with empty (discard) slots, the `()` throw-away, and a
/// destructuring that also names the whole value (`(a, b): t`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Pattern {
    /// An empty position: `()` or an empty pat_list slot; binds nothing.
    Discard { span: SourceSpan },
    /// `x` or const `!x`.
    Name {
        name: String,
        name_span: SourceSpan,
        constant: bool,
        span: SourceSpan,
    },
    /// `(p, …)` destructuring; `: t` / `: !t` also binds the whole value
    /// (the `whole` pattern is then always a `Name`, per the grammar).
    Tuple {
        elements: Vec<Pattern>,
        whole: Option<Box<Pattern>>,
        span: SourceSpan,
    },
}

impl Pattern {
    pub fn span(&self) -> SourceSpan {
        match self {
            Self::Discard { span } | Self::Name { span, .. } | Self::Tuple { span, .. } => *span,
        }
    }
}

/// A lambda parameter (parser.y `id_spec`): `type pattern`, the anonymous
/// `type .`, or `(id_spec, …)` destructuring of one argument value.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum LambdaParam {
    /// Boxed to keep the enum small (a `TypeExpr` plus `Pattern` payload
    /// would dwarf the tuple variant).
    Typed(Box<TypedParam>),
    Tuple {
        elements: Vec<LambdaParam>,
        span: SourceSpan,
    },
}

/// A `type pattern` parameter; the pattern is a discard for the anonymous
/// `type .` form.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TypedParam {
    pub type_expr: TypeExpr,
    pub pattern: Pattern,
    pub span: SourceSpan,
}

/// A parsed type expression (upstream parser.y:792-818), spanned; length-1
/// tuples and unions are collapsed by the grammar helpers, mirroring
/// [`crate::types::Type`]. `TYPE_ID` mentions arrive with typedefs (B5).
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TypeExpr {
    Primitive {
        value: Prim,
        span: SourceSpan,
    },
    /// `[T]`.
    Row {
        component: Box<TypeExpr>,
        span: SourceSpan,
    },
    /// `[*]` — row of as-yet-undetermined component type.
    WildRow {
        span: SourceSpan,
    },
    /// `void` written as an empty variant slot; also the empty arrow sides.
    Void {
        span: SourceSpan,
    },
    Tuple {
        components: Vec<TypeExpr>,
        span: SourceSpan,
    },
    Union {
        variants: Vec<TypeExpr>,
        span: SourceSpan,
    },
    Function {
        argument: Box<TypeExpr>,
        result: Box<TypeExpr>,
        span: SourceSpan,
    },
    /// A typedef name (upstream `TYPE_ID`): an alias from the single-name
    /// `set_type` form, or a tabled type from the bracketed form.
    Named {
        name: String,
        span: SourceSpan,
    },
}

impl TypeExpr {
    pub fn span(&self) -> SourceSpan {
        match self {
            Self::Primitive { span, .. }
            | Self::Row { span, .. }
            | Self::WildRow { span }
            | Self::Void { span }
            | Self::Tuple { span, .. }
            | Self::Union { span, .. }
            | Self::Function { span, .. }
            | Self::Named { span, .. } => *span,
        }
    }

    /// The structural type this expression denotes, resolving typedef
    /// names through the table; an unknown name is an error carrying its
    /// token (upstream can only lex a defined name as `TYPE_ID`).
    pub fn resolve_in(
        &self,
        table: &crate::types::TypeTable,
    ) -> Result<crate::types::Type, SpannedValue<String>> {
        use crate::types::Type;
        match self {
            Self::Primitive { value, .. } => Ok(Type::Primitive(*value)),
            Self::Row { component, .. } => Ok(Type::row(component.resolve_in(table)?)),
            Self::WildRow { .. } => Ok(Type::row(Type::Undetermined)),
            Self::Void { .. } => Ok(Type::void()),
            Self::Tuple { components, .. } => Ok(Type::tuple(
                components
                    .iter()
                    .map(|component| component.resolve_in(table))
                    .collect::<Result<Vec<_>, _>>()?,
            )),
            Self::Union { variants, .. } => Ok(Type::union_of(
                variants
                    .iter()
                    .map(|variant| variant.resolve_in(table))
                    .collect::<Result<Vec<_>, _>>()?,
            )),
            Self::Function {
                argument, result, ..
            } => Ok(Type::function(
                argument.resolve_in(table)?,
                result.resolve_in(table)?,
            )),
            Self::Named { name, span } => table.resolve_name(name).ok_or_else(|| SpannedValue {
                value: name.clone(),
                span: *span,
            }),
        }
    }

    /// The structural type this expression denotes, without any typedef
    /// names in scope (diagnostic-rendering paths; an unexpected name
    /// degrades to undetermined rather than panicking).
    pub fn resolve(&self) -> crate::types::Type {
        self.resolve_in(&crate::types::TypeTable::new())
            .unwrap_or(crate::types::Type::Undetermined)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LetBinding {
    pub pattern: Pattern,
    pub initializer: Expr,
}

#[derive(Debug)]
pub struct ParsedLet {
    pub binding_groups: Vec<Vec<LetBinding>>,
    pub body: Expr,
}

/// The pieces of a `for` loop between `for` and `od` (kept off a bare
/// tuple so the generated parser stays under clippy's complexity limit).
#[derive(Debug)]
pub struct ParsedFor {
    pub pattern: Option<Pattern>,
    pub index: Option<SpannedValue<String>>,
    pub iterable: Expr,
    pub body: Expr,
    pub od: SourceSpan,
}

/// A `set_type` right-hand side (parser.y:753-761 `type_spec`, 786-790
/// `typedef_type`): a plain type alias, a struct whose named fields become
/// projectors, or a union whose named variants become injectors.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TypeSpec {
    Alias(TypeExpr),
    Struct(Vec<TypeField>),
    Union(Vec<TypeField>),
}

/// One field of a struct spec or variant of a union spec: `type name` or
/// the anonymous `type .` form.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TypeField {
    pub type_expr: TypeExpr,
    pub name: Option<SpannedValue<String>>,
    pub span: SourceSpan,
}

/// One `Name = spec` equation of a `set_type` command.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TypeDefinition {
    pub name: SpannedValue<String>,
    pub spec: TypeSpec,
}

/// One branch of a `case … esac` discrimination (parser.y caselist):
/// `tag(pattern): body`, `tag: body`, or the `else body` fallback.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CaseBranch {
    /// The injector tag; `None` for the `else` branch.
    pub tag: Option<SpannedValue<String>>,
    pub pattern: Option<Pattern>,
    pub body: Expr,
    pub span: SourceSpan,
}

impl Expr {
    pub fn span(&self) -> SourceSpan {
        match self {
            Self::Integer { span, .. }
            | Self::Boolean { span, .. }
            | Self::String { span, .. }
            | Self::Tuple { span, .. }
            | Self::List { span, .. }
            | Self::Subscription { span, .. }
            | Self::Slice { span, .. }
            | Self::Identifier { span, .. }
            | Self::Assignment { span, .. }
            | Self::Let { span, .. }
            | Self::Unary { span, .. }
            | Self::Binary { span, .. }
            | Self::OperatorCall { span, .. }
            | Self::Call { span, .. }
            | Self::Lambda { span, .. }
            | Self::Return { span, .. }
            | Self::RecLambda { span, .. }
            | Self::Group { span, .. }
            | Self::Conditional { span, .. }
            | Self::Cast { span, .. }
            | Self::Sequence { span, .. }
            | Self::While { span, .. }
            | Self::Break { span } => *span,
            Self::For(loop_) => loop_.span,
            Self::Case(case) => case.span,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct SliceFlags {
    pub reverse_output: bool,
    pub lower_from_end: bool,
    pub upper_from_end: bool,
}

#[derive(Debug)]
enum PostfixSuffix {
    Subscription {
        index: Expr,
        reversed: bool,
        close: SourceSpan,
    },
    Slice {
        lower: Expr,
        upper: Expr,
        flags: SliceFlags,
        close: SourceSpan,
    },
    Call {
        arguments: Vec<Expr>,
        close: SourceSpan,
    },
    /// A `.selector` suffix (parser.y:321-337), lowered to an application
    /// of the selector to the receiver.
    Selector {
        callee: SelectorCallee,
        span: SourceSpan,
    },
}

/// What follows the dot of a selector (parser.y:321 `selector: unit |
/// ident_expr | operator`): a name resolving through the overload table,
/// an operator token applied like its prefix form, or a literal applied
/// as a function (which conversion rejects unless it is callable).
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum SelectorCallee {
    Identifier(String),
    Operator(FormulaOperator),
    /// Boxed to keep `PostfixSuffix` small.
    Literal(Box<Expr>),
}

/// A top-level Atlas command.
///
/// Global definitions use command syntax and produce definition output;
/// assignments remain expressions and return their assigned value.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Command {
    Expression(Expr),
    Define {
        name: String,
        name_span: SourceSpan,
        value: Expr,
        span: SourceSpan,
    },
    Declare {
        name: String,
        name_span: SourceSpan,
        value_type: Prim,
        span: SourceSpan,
    },
    /// `set_type Name = spec` and `set_type [ Name = spec, … ]`
    /// (parser.y:163-167). Only the bracketed form enters the tabled
    /// type map (enabling recursion and case discrimination).
    SetType {
        definitions: Vec<TypeDefinition>,
        tabled: bool,
        span: SourceSpan,
    },
    /// `whattype target` (parser.y:169-171): a type name prints its
    /// definition, any other expression prints its converted type.
    Whattype {
        target: Expr,
        span: SourceSpan,
    },
}

impl Command {
    pub fn span(&self) -> SourceSpan {
        match self {
            Self::Expression(expression) => expression.span(),
            Self::Define { span, .. }
            | Self::Declare { span, .. }
            | Self::SetType { span, .. }
            | Self::Whattype { span, .. } => *span,
        }
    }
}

pub use crate::types::Prim;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnaryOp {
    Not,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BinaryOp {
    And,
    Or,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Program {
    pub expressions: Vec<Expr>,
}

/// Public parser error. The diagnostic category remains the compatibility
/// boundary; wording can be refined after Atlas oracle comparisons.
pub type ParseError = Diagnostic;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpannedValue<T> {
    pub value: T,
    pub span: SourceSpan,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ParserToken {
    Integer(SpannedValue<BigInt>),
    Boolean(SpannedValue<bool>),
    String(SpannedValue<String>),
    Identifier(SpannedValue<String>),
    Operator(SpannedValue<FormulaOperator>),
    PrimitiveType(SpannedValue<Prim>),
    Becomes(SourceSpan),
    Equals(SourceSpan),
    Star(SourceSpan),
    Bar(SourceSpan),
    Arrow(SourceSpan),
    VoidType(SourceSpan),
    Colon(SourceSpan),
    Comma(SourceSpan),
    LBracket(SourceSpan),
    ReverseLBracket(SourceSpan),
    RBracket(SourceSpan),
    Tilde(SourceSpan),
    Let(SourceSpan),
    In(SourceSpan),
    Begin(SourceSpan),
    End(SourceSpan),
    Then(SourceSpan),
    If(SourceSpan),
    Else(SourceSpan),
    Elif(SourceSpan),
    Fi(SourceSpan),
    And(SourceSpan),
    Or(SourceSpan),
    Not(SourceSpan),
    Return(SourceSpan),
    RecFun(SourceSpan),
    While(SourceSpan),
    For(SourceSpan),
    Do(SourceSpan),
    Od(SourceSpan),
    Break(SourceSpan),
    SetType(SourceSpan),
    Whattype(SourceSpan),
    Case(SourceSpan),
    Esac(SourceSpan),
    /// `!` — the const-binding marker in patterns, never a formula operator.
    Bang(SourceSpan),
    At(SourceSpan),
    Dot(SourceSpan),
    Semicolon(SourceSpan),
    LParen(SourceSpan),
    RParen(SourceSpan),
    Newline(SourceSpan),
    Unsupported(SpannedValue<String>),
}

impl ParserToken {
    fn span(&self) -> SourceSpan {
        match self {
            Self::Integer(value) => value.span,
            Self::Boolean(value) => value.span,
            Self::String(value) => value.span,
            Self::Identifier(value) => value.span,
            Self::Operator(value) => value.span,
            Self::PrimitiveType(value) => value.span,
            Self::Unsupported(value) => value.span,
            Self::Becomes(span)
            | Self::Equals(span)
            | Self::Star(span)
            | Self::Bar(span)
            | Self::Arrow(span)
            | Self::VoidType(span)
            | Self::Colon(span)
            | Self::Comma(span)
            | Self::LBracket(span)
            | Self::ReverseLBracket(span)
            | Self::RBracket(span)
            | Self::Tilde(span)
            | Self::Let(span)
            | Self::In(span)
            | Self::Begin(span)
            | Self::End(span)
            | Self::Then(span)
            | Self::If(span)
            | Self::Else(span)
            | Self::Elif(span)
            | Self::Fi(span)
            | Self::And(span)
            | Self::Or(span)
            | Self::Not(span)
            | Self::Return(span)
            | Self::RecFun(span)
            | Self::While(span)
            | Self::For(span)
            | Self::Do(span)
            | Self::Od(span)
            | Self::Break(span)
            | Self::SetType(span)
            | Self::Whattype(span)
            | Self::Case(span)
            | Self::Esac(span)
            | Self::Bang(span)
            | Self::At(span)
            | Self::Dot(span)
            | Self::Semicolon(span)
            | Self::LParen(span)
            | Self::RParen(span)
            | Self::Newline(span) => *span,
        }
    }
}

impl fmt::Display for ParserToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Integer(_) => "integer",
            Self::Boolean(_) => "boolean",
            Self::String(_) => "string",
            Self::Identifier(_) => "identifier",
            Self::Operator(operator) => operator.value.symbol.as_str(),
            Self::PrimitiveType(_) => "primitive type",
            Self::Becomes(_) => ":=",
            Self::Equals(_) => "=",
            Self::Star(_) => "*",
            Self::Bar(_) => "|",
            Self::Arrow(_) => "->",
            Self::VoidType(_) => "void",
            Self::Colon(_) => ":",
            Self::Comma(_) => ",",
            Self::LBracket(_) => "[",
            Self::ReverseLBracket(_) => "~[",
            Self::RBracket(_) => "]",
            Self::Tilde(_) => "~",
            Self::Let(_) => "let",
            Self::In(_) => "in",
            Self::Begin(_) => "begin",
            Self::End(_) => "end",
            Self::Then(_) => "then",
            Self::If(_) => "if",
            Self::Else(_) => "else",
            Self::Elif(_) => "elif",
            Self::Fi(_) => "fi",
            Self::And(_) => "and",
            Self::Or(_) => "or",
            Self::Not(_) => "not",
            Self::Return(_) => "return",
            Self::RecFun(_) => "rec_fun",
            Self::While(_) => "while",
            Self::For(_) => "for",
            Self::Do(_) => "do",
            Self::Od(_) => "od",
            Self::Break(_) => "break",
            Self::SetType(_) => "set_type",
            Self::Whattype(_) => "whattype",
            Self::Case(_) => "case",
            Self::Esac(_) => "esac",
            Self::Bang(_) => "!",
            Self::At(_) => "@",
            Self::Dot(_) => ".",
            Self::Semicolon(_) => ";",
            Self::LParen(_) => "(",
            Self::RParen(_) => ")",
            Self::Newline(_) => "newline",
            Self::Unsupported(_) => "unsupported token",
        })
    }
}

type Spanned<T> = Result<(usize, T, usize), ()>;

struct TokenStream {
    tokens: std::vec::IntoIter<(ParserToken, SourceSpan)>,
    index: usize,
}

impl TokenStream {
    fn new(tokens: Vec<(ParserToken, SourceSpan)>) -> Self {
        Self {
            tokens: tokens.into_iter(),
            index: 0,
        }
    }
}

impl Iterator for TokenStream {
    type Item = Spanned<ParserToken>;

    fn next(&mut self) -> Option<Self::Item> {
        let (token, _) = self.tokens.next()?;
        let start = self.index;
        self.index += 1;
        Some(Ok((start, token, self.index)))
    }
}

fn parser_tokens_from_tokens(
    tokens: impl IntoIterator<Item = Token>,
) -> Result<Vec<(ParserToken, SourceSpan)>, ParseError> {
    let tokens = tokens.into_iter().collect::<Vec<_>>();
    let reversal_tildes = tokens
        .iter()
        .enumerate()
        .map(|(index, token)| {
            if !matches!(token.kind, TokenKind::Punctuation('~')) {
                return false;
            }
            match tokens.get(index + 1).map(|next| &next.kind) {
                Some(TokenKind::Punctuation(':' | ']' | ',')) => true,
                Some(TokenKind::Keyword(word)) => {
                    matches!(word.as_str(), "do" | "od" | "if" | "for")
                }
                _ => false,
            }
        })
        .collect::<Vec<_>>();
    tokens
        .into_iter()
        .zip(reversal_tildes)
        .filter_map(|(token, reversal_tilde)| {
            let span = token.span;
            match token.kind {
                TokenKind::Eof => None,
                TokenKind::Integer => match token.lexeme.parse::<BigInt>() {
                    Ok(value) => Some(Ok((
                        ParserToken::Integer(SpannedValue { value, span }),
                        span,
                    ))),
                    Err(_) => Some(Err(Diagnostic::new(
                        ErrorKind::Lexical,
                        "invalid integer",
                        Some(span),
                    ))),
                },
                TokenKind::String => Some(Ok((
                    ParserToken::String(SpannedValue {
                        value: token.value.unwrap_or_default(),
                        span,
                    }),
                    span,
                ))),
                TokenKind::PrimitiveType(name) => {
                    if name == "void" {
                        // Upstream maps the name to the empty tuple type.
                        return Some(Ok((ParserToken::VoidType(span), span)));
                    }
                    let value = Prim::ALL
                        .into_iter()
                        .find(|prim| prim.name() == name.as_str());
                    let token = value.map_or_else(
                        || ParserToken::Unsupported(SpannedValue { value: name, span }),
                        |value| ParserToken::PrimitiveType(SpannedValue { value, span }),
                    );
                    Some(Ok((token, span)))
                }
                TokenKind::Identifier => Some(Ok((
                    ParserToken::Identifier(SpannedValue {
                        value: token.lexeme,
                        span,
                    }),
                    span,
                ))),
                TokenKind::Keyword(word) => {
                    let token = match word.as_str() {
                        "true" => ParserToken::Boolean(SpannedValue { value: true, span }),
                        "false" => ParserToken::Boolean(SpannedValue { value: false, span }),
                        "and" => ParserToken::And(span),
                        "or" => ParserToken::Or(span),
                        "not" => ParserToken::Not(span),
                        "let" => ParserToken::Let(span),
                        "in" => ParserToken::In(span),
                        "begin" => ParserToken::Begin(span),
                        "end" => ParserToken::End(span),
                        "then" => ParserToken::Then(span),
                        "if" => ParserToken::If(span),
                        "else" => ParserToken::Else(span),
                        "elif" => ParserToken::Elif(span),
                        "fi" => ParserToken::Fi(span),
                        "return" => ParserToken::Return(span),
                        "rec_fun" => ParserToken::RecFun(span),
                        "while" => ParserToken::While(span),
                        "for" => ParserToken::For(span),
                        "do" => ParserToken::Do(span),
                        "od" => ParserToken::Od(span),
                        "break" => ParserToken::Break(span),
                        "set_type" => ParserToken::SetType(span),
                        "whattype" => ParserToken::Whattype(span),
                        "case" => ParserToken::Case(span),
                        "esac" => ParserToken::Esac(span),
                        _ => ParserToken::Unsupported(SpannedValue { value: word, span }),
                    };
                    Some(Ok((token, span)))
                }
                TokenKind::Operator(operator) => {
                    let token = match operator.as_str() {
                        ":=" => ParserToken::Becomes(span),
                        "=" => ParserToken::Equals(span),
                        "*" => ParserToken::Star(span),
                        "->" => ParserToken::Arrow(span),
                        "~[" => ParserToken::ReverseLBracket(span),
                        // Bare `!` is the const-binding marker in patterns.
                        "!" => ParserToken::Bang(span),
                        _ => parser_operator(operator, span).unwrap_or_else(|operator| {
                            ParserToken::Unsupported(SpannedValue {
                                value: operator,
                                span,
                            })
                        }),
                    };
                    Some(Ok((token, span)))
                }
                TokenKind::Punctuation(punctuation) => {
                    let token = match punctuation {
                        '(' => ParserToken::LParen(span),
                        ')' => ParserToken::RParen(span),
                        ':' => ParserToken::Colon(span),
                        ',' => ParserToken::Comma(span),
                        '[' => ParserToken::LBracket(span),
                        ']' => ParserToken::RBracket(span),
                        '|' => ParserToken::Bar(span),
                        // `@` and `.` are expression punctuation here; the
                        // `<file` directive scanner reads filenames before
                        // any of these tokens exist, so they cannot clash.
                        '@' => ParserToken::At(span),
                        '.' => ParserToken::Dot(span),
                        ';' => ParserToken::Semicolon(span),
                        '~' if reversal_tilde => ParserToken::Tilde(span),
                        '~' => parser_operator("~".to_owned(), span)
                            .expect("tilde has a fixed Atlas priority"),
                        _ => ParserToken::Unsupported(SpannedValue {
                            value: punctuation.to_string(),
                            span,
                        }),
                    };
                    Some(Ok((token, span)))
                }
                TokenKind::Unsupported(value) => Some(Ok((
                    ParserToken::Unsupported(SpannedValue { value, span }),
                    span,
                ))),
                // Directives are intercepted by the session frame; one that
                // reaches the expression parser is a plain syntax error.
                TokenKind::Directive(_) => Some(Ok((
                    ParserToken::Unsupported(SpannedValue {
                        value: token.lexeme,
                        span,
                    }),
                    span,
                ))),
                // Operate-assign enters the grammar with the assignment
                // family (phase B stage B4); a syntax error until then.
                TokenKind::OperatorBecomes(_) => Some(Ok((
                    ParserToken::Unsupported(SpannedValue {
                        value: token.lexeme,
                        span,
                    }),
                    span,
                ))),
                TokenKind::Newline => Some(Ok((ParserToken::Newline(span), span))),
            }
        })
        .collect()
}

fn parser_operator(symbol: String, span: SourceSpan) -> Result<ParserToken, String> {
    let priority = match symbol.as_str() {
        "<" | "<=" | ">" | ">=" | "=" | "!=" => 2,
        "+" | "-" => 4,
        "*" | "%" | "/" | "&" | "\\" | "\\%" => 6,
        "^" => 7,
        "#" | "##" | "~" => 8,
        _ => return Err(symbol),
    };
    let value = FormulaOperator::new(symbol, priority).with_span(span);
    Ok(ParserToken::Operator(SpannedValue { value, span }))
}

fn parser_tokens(source: &SourceText) -> Result<Vec<(ParserToken, SourceSpan)>, ParseError> {
    let tokens = tokenize(source).map_err(|mut errors| errors.remove(0))?;
    parser_tokens_from_tokens(tokens)
}

/// Parse an Atlas source buffer into the current expression-level AST.
pub fn parse(source: &SourceText) -> Result<Program, ParseError> {
    let tokens = parser_tokens(source)?;
    let spans: Vec<SourceSpan> = tokens.iter().map(|(_, span)| *span).collect();
    grammar::ProgramParser::new()
        .parse(TokenStream::new(tokens))
        .map_err(|error| syntax_error(error, source, &spans))
}

/// Parse one already-delimited Atlas command. The lexer remains responsible
/// for command boundaries; this adapter deliberately does not tokenize the
/// rest of the source, so session state can change before the next command.
pub fn parse_command(tokens: &[Token], source: &SourceText) -> Result<Command, ParseError> {
    let parsed = parser_tokens_from_tokens(tokens.iter().cloned())?;
    let spans: Vec<SourceSpan> = parsed.iter().map(|(_, span)| *span).collect();
    grammar::CommandParser::new()
        .parse(TokenStream::new(parsed))
        .map_err(|error| syntax_error(error, source, &spans))
}

fn syntax_error(
    error: lalrpop_util::ParseError<usize, ParserToken, ()>,
    source: &SourceText,
    spans: &[SourceSpan],
) -> ParseError {
    let (message, span) = match error {
        lalrpop_util::ParseError::InvalidToken { location } => (
            "invalid token".to_string(),
            spans
                .get(location)
                .copied()
                .or_else(|| Some(source.span(source.as_str().len(), source.as_str().len()))),
        ),
        lalrpop_util::ParseError::UnrecognizedEof { location, .. } => (
            "unexpected end of input".to_string(),
            spans
                .get(location)
                .copied()
                .or_else(|| Some(source.span(source.as_str().len(), source.as_str().len()))),
        ),
        lalrpop_util::ParseError::UnrecognizedToken {
            token: (start, token, _),
            ..
        }
        | lalrpop_util::ParseError::ExtraToken {
            token: (start, token, _),
        } => {
            // The oracle reports the bison token name; identifiers and the
            // reserved-word keywords get the exact wording, everything else
            // keeps the generic fallback until a fuller token table is needed.
            let message = match bison_token_name(&token) {
                Some(name) => format!("syntax error, unexpected {name}"),
                None => "unexpected token".to_string(),
            };
            (
                message,
                spans.get(start).copied().or_else(|| Some(token.span())),
            )
        }
        lalrpop_util::ParseError::User { .. } => ("parser input error".to_string(), None),
    };
    Diagnostic::new(ErrorKind::Syntax, message, span)
}

/// The bison token name used by the oracle's `syntax error, unexpected X`
/// wording, for the tokens we match exactly: identifiers and the
/// reserved-word keywords (bison names those after their uppercase
/// spelling). Every other token keeps the generic fallback.
fn bison_token_name(token: &ParserToken) -> Option<&'static str> {
    match token {
        ParserToken::Identifier(_) => Some("IDENT"),
        ParserToken::If(_) => Some("IF"),
        ParserToken::Then(_) => Some("THEN"),
        ParserToken::Else(_) => Some("ELSE"),
        ParserToken::Elif(_) => Some("ELIF"),
        ParserToken::Fi(_) => Some("FI"),
        ParserToken::Let(_) => Some("LET"),
        ParserToken::In(_) => Some("IN"),
        ParserToken::Begin(_) => Some("BEGIN"),
        ParserToken::End(_) => Some("END"),
        ParserToken::And(_) => Some("AND"),
        ParserToken::Or(_) => Some("OR"),
        ParserToken::Not(_) => Some("NOT"),
        ParserToken::Return(_) => Some("RETURN"),
        ParserToken::RecFun(_) => Some("REC_FUN"),
        ParserToken::While(_) => Some("WHILE"),
        ParserToken::For(_) => Some("FOR"),
        ParserToken::Do(_) => Some("DO"),
        ParserToken::Od(_) => Some("OD"),
        ParserToken::Break(_) => Some("BREAK"),
        ParserToken::SetType(_) => Some("SET_TYPE"),
        ParserToken::Whattype(_) => Some("WHATTYPE"),
        ParserToken::Case(_) => Some("CASE"),
        ParserToken::Esac(_) => Some("ESAC"),
        ParserToken::Colon(_) => Some("':'"),
        ParserToken::VoidType(_) => Some("VOID"),
        _ => None,
    }
}

fn join_span(start: SourceSpan, end: SourceSpan) -> SourceSpan {
    debug_assert_eq!(start.source_id(), end.source_id());
    SourceSpan::new(
        start.source_id(),
        start.byte_start(),
        end.byte_end(),
        start.start,
        end.end,
    )
}

fn unary(op: UnaryOp, operand: Expr, operator: SourceSpan) -> Expr {
    Expr::Unary {
        op,
        span: join_span(operator, operand.span()),
        operand: Box::new(operand),
    }
}

fn binary(op: BinaryOp, lhs: Expr, rhs: Expr) -> Expr {
    let span = join_span(lhs.span(), rhs.span());
    Expr::Binary {
        op,
        span,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    }
}

fn assignment(target: SpannedValue<String>, value: Expr) -> Expr {
    Expr::Assignment {
        name: target.value,
        target_span: target.span,
        span: join_span(target.span, value.span()),
        value: Box::new(value),
    }
}

fn sequence(first: Expr, rest: Expr) -> Expr {
    Expr::Sequence {
        span: join_span(first.span(), rest.span()),
        first: Box::new(first),
        second: Box::new(rest),
    }
}

fn while_expression(while_span: SourceSpan, tail: (Option<Expr>, Expr, SourceSpan)) -> Expr {
    let (condition, body, od) = tail;
    Expr::While {
        span: join_span(while_span, od),
        condition: condition.map(Box::new),
        body: Box::new(body),
    }
}

fn for_expression(for_span: SourceSpan, parsed: ParsedFor) -> Expr {
    Expr::For(Box::new(ForLoop {
        pattern: parsed.pattern,
        index: parsed.index,
        span: join_span(for_span, parsed.od),
        iterable: Box::new(parsed.iterable),
        body: Box::new(parsed.body),
    }))
}

fn let_expression(let_span: SourceSpan, parsed: ParsedLet) -> Expr {
    Expr::Let {
        binding_groups: parsed.binding_groups,
        span: join_span(let_span, parsed.body.span()),
        body: Box::new(parsed.body),
    }
}

fn tuple_expression(open: SourceSpan, elements: Vec<Expr>, close: SourceSpan) -> Expr {
    Expr::Tuple {
        elements,
        span: join_span(open, close),
    }
}

fn list_expression(open: SourceSpan, elements: Vec<Expr>, close: SourceSpan) -> Expr {
    Expr::List {
        elements,
        span: join_span(open, close),
    }
}

fn subscription(array: Expr, index: Expr, reversed: bool, close: SourceSpan) -> Expr {
    Expr::Subscription {
        span: join_span(array.span(), close),
        array: Box::new(array),
        index: Box::new(index),
        reversed,
    }
}

fn postfix(array: Expr, suffix: PostfixSuffix) -> Expr {
    match suffix {
        PostfixSuffix::Subscription {
            index,
            reversed,
            close,
        } => subscription(array, index, reversed, close),
        PostfixSuffix::Slice {
            lower,
            upper,
            flags,
            close,
        } => Expr::Slice {
            span: join_span(array.span(), close),
            array: Box::new(array),
            lower: Box::new(lower),
            upper: Box::new(upper),
            flags,
        },
        PostfixSuffix::Call { arguments, close } => Expr::Call {
            span: join_span(array.span(), close),
            callee: Box::new(array),
            arguments,
        },
        PostfixSuffix::Selector { callee, span } => {
            let call_span = join_span(array.span(), span);
            match callee {
                SelectorCallee::Identifier(name) => Expr::Call {
                    span: call_span,
                    callee: Box::new(Expr::Identifier { name, span }),
                    arguments: vec![array],
                },
                // An operator selector resolves exactly like the prefix
                // form (`2.-` is unary minus applied to 2); the span runs
                // receiver-first, unlike a prefix call.
                SelectorCallee::Operator(operator) => Expr::OperatorCall {
                    span: call_span,
                    operator,
                    arguments: vec![array],
                },
                SelectorCallee::Literal(callee) => Expr::Call {
                    span: call_span,
                    callee,
                    arguments: vec![array],
                },
            }
        }
    }
}

fn call_suffix(arguments: Vec<Expr>, close: SourceSpan) -> PostfixSuffix {
    PostfixSuffix::Call { arguments, close }
}

/// `receiver.name` — upstream lowers the selector to `name(receiver)`
/// (parser.y:333-337 `make_application_node`).
fn selector_suffix(name: SpannedValue<String>) -> PostfixSuffix {
    PostfixSuffix::Selector {
        callee: SelectorCallee::Identifier(name.value),
        span: name.span,
    }
}

/// `receiver.op` — the operator applies to the receiver alone
/// (parser.y:312 `operator` as a selector), resolving like its prefix
/// form through the overload table.
fn operator_selector(operator: FormulaOperator) -> PostfixSuffix {
    PostfixSuffix::Selector {
        span: operator.span.expect("grammar operators carry spans"),
        callee: SelectorCallee::Operator(operator),
    }
}

/// `receiver.unit` — the literal applies as a function (parser.y:321
/// `selector: unit`).
fn unit_selector(callee: Expr) -> PostfixSuffix {
    PostfixSuffix::Selector {
        span: callee.span(),
        callee: SelectorCallee::Literal(Box::new(callee)),
    }
}

/// A lambda literal; `open` is the `(` or `@` that starts it. The body
/// greedily takes the rest of the expression (parser.y:224-238).
fn lambda(open: SourceSpan, parameters: Vec<LambdaParam>, body: Expr) -> Expr {
    Expr::Lambda {
        parameters,
        span: join_span(open, body.span()),
        body: Box::new(body),
    }
}

fn lambda_parameter(type_expr: TypeExpr, pattern: Pattern) -> LambdaParam {
    LambdaParam::Typed(Box::new(TypedParam {
        span: join_span(type_expr.span(), pattern.span()),
        type_expr,
        pattern,
    }))
}

/// The anonymous `type .` parameter: the argument converts against the
/// type but binds no name (parser.y `id_spec: type '.'`).
fn anonymous_parameter(type_expr: TypeExpr, dot: SourceSpan) -> LambdaParam {
    LambdaParam::Typed(Box::new(TypedParam {
        span: join_span(type_expr.span(), dot),
        type_expr,
        pattern: Pattern::Discard { span: dot },
    }))
}

/// `(id_spec, …)` destructures one argument value per position. A single
/// spec in parentheses is plain grouping and collapses, mirroring the
/// length-1 tuple collapse in [`TypeExpr`].
fn tuple_parameter(
    open: SourceSpan,
    mut elements: Vec<LambdaParam>,
    close: SourceSpan,
) -> LambdaParam {
    if elements.len() == 1 {
        return elements.pop().expect("one element");
    }
    LambdaParam::Tuple {
        span: join_span(open, close),
        elements,
    }
}

fn lambda_parameters(first: LambdaParam, rest: Vec<LambdaParam>) -> Vec<LambdaParam> {
    let mut parameters = Vec::with_capacity(rest.len() + 1);
    parameters.push(first);
    parameters.extend(rest);
    parameters
}

/// `x` in pattern position.
fn pattern_name(name: SpannedValue<String>) -> Pattern {
    Pattern::Name {
        span: name.span,
        name: name.value,
        name_span: name.span,
        constant: false,
    }
}

/// `!x` in pattern position: a constant binding (parser.y `pattern: '!' IDENT`).
fn const_pattern_name(bang: SourceSpan, name: SpannedValue<String>) -> Pattern {
    Pattern::Name {
        span: join_span(bang, name.span),
        name: name.value,
        name_span: name.span,
        constant: true,
    }
}

/// The `()` throw-away pattern.
fn pattern_discard(open: SourceSpan, close: SourceSpan) -> Pattern {
    Pattern::Discard {
        span: join_span(open, close),
    }
}

/// What follows the first slot of a parenthesised pattern: `)` makes it
/// grouping (collapses), a comma makes it a destructuring slot list that
/// may name the whole value (parser.y:708-749).
pub(crate) enum PatternTail {
    Group,
    Slots(Box<SlotTail>),
}

pub(crate) struct SlotTail {
    pub comma: SourceSpan,
    pub second: Option<Pattern>,
    pub rest: Vec<Option<Pattern>>,
    pub close: SourceSpan,
    pub whole: Option<Pattern>,
}

fn finish_pattern(open: SourceSpan, first: Pattern, tail: PatternTail) -> Pattern {
    match tail {
        PatternTail::Group => first,
        PatternTail::Slots(slots) => {
            let slots = *slots;
            pattern_tuple(
                open,
                pattern_slots(Some(first), slots.comma, slots.second, slots.rest),
                slots.close,
                slots.whole,
            )
        }
    }
}

/// `(p, …)` tuple destructuring, optionally naming the whole value with
/// `: t` or const `: !t`.
fn pattern_tuple(
    open: SourceSpan,
    elements: Vec<Pattern>,
    close: SourceSpan,
    whole: Option<Pattern>,
) -> Pattern {
    Pattern::Tuple {
        span: join_span(open, close),
        elements,
        whole: whole.map(Box::new),
    }
}

/// The slots of a `pat_list`: an empty slot is a discard. Gap spans borrow
/// the nearest comma (the first one for leading slots); discard spans never
/// surface in diagnostics since a discard binds nothing.
fn pattern_slots(
    first: Option<Pattern>,
    comma: SourceSpan,
    second: Option<Pattern>,
    rest: Vec<Option<Pattern>>,
) -> Vec<Pattern> {
    let mut slots = Vec::with_capacity(rest.len() + 2);
    slots.push(first.unwrap_or(Pattern::Discard { span: comma }));
    slots.push(second.unwrap_or(Pattern::Discard { span: comma }));
    slots.extend(
        rest.into_iter()
            .map(|slot| slot.unwrap_or(Pattern::Discard { span: comma })),
    );
    slots
}

fn return_expression(return_span: SourceSpan, value: Expr) -> Expr {
    Expr::Return {
        span: join_span(return_span, value.span()),
        value: Box::new(value),
    }
}

/// `rec_fun name(params) result: body` (parser.y:231).
fn rec_lambda(
    rec_span: SourceSpan,
    self_name: SpannedValue<String>,
    parameters: Vec<LambdaParam>,
    result_type: TypeExpr,
    body: Expr,
) -> Expr {
    Expr::RecLambda {
        span: join_span(rec_span, body.span()),
        self_name: self_name.value,
        self_span: self_name.span,
        parameters,
        result_type: Box::new(result_type),
        body: Box::new(body),
    }
}

/// `name(params) = body` in a let declaration desugars to a plain lambda
/// binding (parser.y:251-257).
fn function_binding(
    target: SpannedValue<String>,
    open: SourceSpan,
    parameters: Vec<LambdaParam>,
    body: Expr,
) -> LetBinding {
    let_binding(target, lambda(open, parameters, body))
}

/// `rec_fun name(params) = result: body` in a let declaration desugars to
/// `name = rec_fun name (params) result: body` (parser.y:256-257).
fn rec_function_binding(
    rec_span: SourceSpan,
    target: SpannedValue<String>,
    parameters: Vec<LambdaParam>,
    result_type: TypeExpr,
    body: Expr,
) -> LetBinding {
    let initializer = rec_lambda(rec_span, target.clone(), parameters, result_type, body);
    let_binding(target, initializer)
}

fn subscription_suffix(index: Expr, reversed: bool, close: SourceSpan) -> PostfixSuffix {
    PostfixSuffix::Subscription {
        index,
        reversed,
        close,
    }
}

fn slice_suffix(
    lower: Option<Expr>,
    upper: Option<Expr>,
    reverse_output: bool,
    lower_from_end: bool,
    upper_from_end: bool,
    colon: SourceSpan,
    close: SourceSpan,
) -> PostfixSuffix {
    let lower_from_end = lower.is_some() && lower_from_end;
    let upper_from_end = upper.is_none() || upper_from_end;
    PostfixSuffix::Slice {
        lower: lower.unwrap_or_else(|| zero_expression(colon)),
        upper: upper.unwrap_or_else(|| zero_expression(close)),
        flags: SliceFlags {
            reverse_output,
            lower_from_end,
            upper_from_end,
        },
        close,
    }
}

fn zero_expression(span: SourceSpan) -> Expr {
    Expr::Integer {
        value: BigInt::from(0),
        span,
    }
}

fn expression_list(first: Expr, rest: Vec<Expr>) -> Vec<Expr> {
    let mut elements = Vec::with_capacity(rest.len() + 1);
    elements.push(first);
    elements.extend(rest);
    elements
}

fn let_binding(target: SpannedValue<String>, initializer: Expr) -> LetBinding {
    LetBinding {
        pattern: pattern_name(target),
        initializer,
    }
}

/// `pattern = expr` in a let declaration (parser.y:247).
fn pattern_binding(pattern: Pattern, initializer: Expr) -> LetBinding {
    LetBinding {
        pattern,
        initializer,
    }
}

fn let_bindings(first: LetBinding, rest: Vec<LetBinding>) -> Vec<LetBinding> {
    let mut bindings = Vec::with_capacity(rest.len() + 1);
    bindings.push(first);
    bindings.extend(rest);
    bindings
}

fn finish_let(binding_group: Vec<LetBinding>, body: Expr) -> ParsedLet {
    ParsedLet {
        binding_groups: vec![binding_group],
        body,
    }
}

fn prepend_let_group(binding_group: Vec<LetBinding>, mut tail: ParsedLet) -> ParsedLet {
    tail.binding_groups.insert(0, binding_group);
    tail
}

fn definition(target: SpannedValue<String>, value: Expr) -> Command {
    Command::Define {
        name: target.value,
        name_span: target.span,
        span: join_span(target.span, value.span()),
        value,
    }
}

fn set_type_command(
    set_type_span: SourceSpan,
    definitions: Vec<TypeDefinition>,
    tabled: bool,
    close: SourceSpan,
) -> Command {
    Command::SetType {
        definitions,
        tabled,
        span: join_span(set_type_span, close),
    }
}

fn whattype_command(whattype_span: SourceSpan, target: Expr) -> Command {
    Command::Whattype {
        span: join_span(whattype_span, target.span()),
        target,
    }
}

fn type_definition(name: SpannedValue<String>, spec: TypeSpec) -> TypeDefinition {
    TypeDefinition { name, spec }
}

fn named_field(type_expr: TypeExpr, name: SpannedValue<String>) -> TypeField {
    TypeField {
        span: join_span(type_expr.span(), name.span),
        type_expr,
        name: Some(name),
    }
}

fn anonymous_field(type_expr: TypeExpr, dot: SourceSpan) -> TypeField {
    TypeField {
        span: join_span(type_expr.span(), dot),
        type_expr,
        name: None,
    }
}

/// End span of a `set_type` right-hand side (diagnostics only).
fn type_spec_span(spec: &TypeSpec) -> SourceSpan {
    match spec {
        TypeSpec::Alias(type_expr) => type_expr.span(),
        TypeSpec::Struct(fields) | TypeSpec::Union(fields) => {
            fields.last().expect("specs hold at least two fields").span
        }
    }
}

fn case_expression(
    case_span: SourceSpan,
    subject: Expr,
    branches: Vec<CaseBranch>,
    esac: SourceSpan,
) -> Expr {
    Expr::Case(Box::new(CaseExpr {
        subject,
        branches,
        span: join_span(case_span, esac),
    }))
}

fn case_branch(tag: SpannedValue<String>, pattern: Option<Pattern>, body: Expr) -> CaseBranch {
    CaseBranch {
        span: join_span(tag.span, body.span()),
        tag: Some(tag),
        pattern,
        body,
    }
}

fn else_branch(else_span: SourceSpan, body: Expr) -> CaseBranch {
    CaseBranch {
        tag: None,
        pattern: None,
        span: join_span(else_span, body.span()),
        body,
    }
}

/// The pieces of an `if` tail, before the opening span is known.
pub(crate) struct ParsedIf {
    condition: Expr,
    then_branch: Expr,
    else_branch: Option<Expr>,
    close: SourceSpan,
}

fn if_tail(
    condition: Expr,
    then_branch: Expr,
    else_branch: Option<Expr>,
    close: SourceSpan,
) -> ParsedIf {
    ParsedIf {
        condition,
        then_branch,
        else_branch,
        close,
    }
}

/// `elif` nests: the tail becomes this level's else branch.
fn elif_tail(condition: Expr, then_branch: Expr, tail: ParsedIf) -> ParsedIf {
    let close = tail.close;
    let nested = finish_conditional(condition.span(), tail);
    ParsedIf {
        condition,
        then_branch,
        else_branch: Some(nested),
        close,
    }
}

fn finish_conditional(open: SourceSpan, tail: ParsedIf) -> Expr {
    let span = join_span(open, tail.close);
    let else_branch = tail.else_branch.unwrap_or(Expr::Tuple {
        elements: Vec::new(),
        span: tail.close,
    });
    Expr::Conditional {
        condition: Box::new(tail.condition),
        then_branch: Box::new(tail.then_branch),
        else_branch: Box::new(else_branch),
        span,
    }
}

fn cast_expression(target: TypeExpr, body: Expr) -> Expr {
    let span = SourceSpan::new(
        target.span().source_id(),
        target.span().byte_start(),
        body.span().byte_end(),
        target.span().start,
        body.span().end,
    );
    Expr::Cast {
        target,
        body: Box::new(body),
        span,
    }
}

fn type_primitive(prim: SpannedValue<Prim>) -> TypeExpr {
    TypeExpr::Primitive {
        value: prim.value,
        span: prim.span,
    }
}

/// One `|`-separated slot of a union list: `None` is an empty (void) slot.
type TypeVariantSlot = Option<Vec<TypeExpr>>;

fn type_variant(first: TypeExpr, rest: Vec<TypeExpr>) -> Vec<TypeExpr> {
    let mut components = vec![first];
    components.extend(rest);
    components
}

/// Assemble a comma-joined variant into a single type at `span`: empty is
/// void, one component is itself, more make a tuple.
fn variant_type(components: TypeVariantSlot, span: SourceSpan) -> TypeExpr {
    match components {
        None => TypeExpr::Void { span },
        Some(mut components) if components.len() == 1 => {
            components.pop().expect("length was checked")
        }
        Some(components) => TypeExpr::Tuple { components, span },
    }
}

/// Assemble the `|`-separated variant slots into a single type at `span`.
fn union_type(variants: Vec<TypeVariantSlot>, span: SourceSpan) -> TypeExpr {
    let mut resolved: Vec<TypeExpr> = variants
        .into_iter()
        .map(|variant| variant_type(variant, span))
        .collect();
    if resolved.len() == 1 {
        resolved.pop().expect("length was checked")
    } else {
        TypeExpr::Union {
            variants: resolved,
            span,
        }
    }
}

fn type_union_start(variant: TypeVariantSlot, leading_empty: bool) -> Vec<TypeVariantSlot> {
    if leading_empty {
        vec![None, variant]
    } else {
        vec![variant]
    }
}

fn type_union_append(
    mut variants: Vec<TypeVariantSlot>,
    variant: TypeVariantSlot,
) -> Vec<TypeVariantSlot> {
    variants.push(variant);
    variants
}

fn type_row(open: SourceSpan, inner: Vec<TypeVariantSlot>, close: SourceSpan) -> TypeExpr {
    let span = join_span(open, close);
    TypeExpr::Row {
        component: Box::new(union_type(inner, span)),
        span,
    }
}

fn type_wild_row(open: SourceSpan, close: SourceSpan) -> TypeExpr {
    TypeExpr::WildRow {
        span: join_span(open, close),
    }
}

fn type_group(open: SourceSpan, inner: Vec<TypeVariantSlot>, close: SourceSpan) -> TypeExpr {
    // Parenthesised type lists have no extra wrapper: the parens only
    // delimit, exactly as upstream builds the tuple/union directly.
    union_type(inner, join_span(open, close))
}

fn type_function(
    open: SourceSpan,
    argument: Option<Vec<TypeVariantSlot>>,
    result: Option<Vec<TypeVariantSlot>>,
    close: SourceSpan,
) -> TypeExpr {
    let span = join_span(open, close);
    let side = |list: Option<Vec<TypeVariantSlot>>| match list {
        None => TypeExpr::Void { span },
        Some(variants) => union_type(variants, span),
    };
    TypeExpr::Function {
        argument: Box::new(side(argument)),
        result: Box::new(side(result)),
        span,
    }
}

fn declaration(target: SpannedValue<String>, value_type: SpannedValue<Prim>) -> Command {
    Command::Declare {
        name: target.value,
        name_span: target.span,
        span: join_span(target.span, value_type.span),
        value_type: value_type.value,
    }
}

fn start_binary_formula(lhs: Expr, operator: FormulaOperator) -> FormulaStack<Expr> {
    start_formula(lhs, operator)
}

fn start_prefix_formula(operator: FormulaOperator) -> FormulaStack<Expr> {
    start_unary_formula(operator)
}

fn extend_operator_formula(
    stack: FormulaStack<Expr>,
    operand: Expr,
    operator: FormulaOperator,
) -> FormulaStack<Expr> {
    extend_formula(stack, operand, operator)
}

fn finish_operator_formula(stack: FormulaStack<Expr>, operand: Expr) -> Expr {
    expression_from_formula(end_formula(stack, operand))
}

fn prefix_operator_call(operator: FormulaOperator, operand: Expr) -> Expr {
    operator_call(operator, vec![operand])
}

fn expression_from_formula(tree: FormulaTree<Expr>) -> Expr {
    match tree {
        FormulaTree::Operand(expression) => expression,
        FormulaTree::Unary { operator, operand } => {
            let operand = expression_from_formula(*operand);
            operator_call(operator, vec![operand])
        }
        FormulaTree::Binary {
            operator,
            left,
            right,
        } => {
            let left = expression_from_formula(*left);
            let right = expression_from_formula(*right);
            operator_call(operator, vec![left, right])
        }
    }
}

fn operator_call(operator: FormulaOperator, arguments: Vec<Expr>) -> Expr {
    debug_assert!(matches!(arguments.len(), 1 | 2));
    let span = match arguments.as_slice() {
        [operand] => operator
            .span
            .map(|operator_span| join_span(operator_span, operand.span()))
            .unwrap_or_else(|| operand.span()),
        [left, right] => join_span(left.span(), right.span()),
        _ => unreachable!("Atlas formula operators have arity one or two"),
    };
    Expr::OperatorCall {
        operator,
        arguments,
        span,
    }
}

/// Compact rendering of an expression, without the source's spacing; the
/// oracle's expression printer produces the same shape in diagnostics that
/// quote an expression (`x:=2` in the constant-assignment error).
pub(crate) fn compact_expression(expression: &Expr) -> String {
    match expression {
        Expr::Integer { value, .. } => value.to_string(),
        Expr::Boolean { value, .. } => value.to_string(),
        Expr::String { value, .. } => format!("\"{value}\""),
        Expr::Tuple { elements, .. } => format!("({})", compact_expressions(elements)),
        Expr::List { elements, .. } => format!("[{}]", compact_expressions(elements)),
        Expr::Subscription {
            array,
            index,
            reversed,
            ..
        } => format!(
            "{}{}{}]",
            compact_expression(array),
            if *reversed { "~[" } else { "[" },
            compact_expression(index)
        ),
        Expr::Slice {
            array,
            lower,
            upper,
            ..
        } => format!(
            "{}[{}:{}]",
            compact_expression(array),
            compact_expression(lower),
            compact_expression(upper)
        ),
        Expr::Identifier { name, .. } => name.clone(),
        Expr::Assignment { name, value, .. } => {
            format!("{name}:={}", compact_expression(value))
        }
        Expr::Let {
            binding_groups,
            body,
            ..
        } => {
            let groups = binding_groups
                .iter()
                .map(|bindings| {
                    bindings
                        .iter()
                        .map(|binding| {
                            format!(
                                "{} = {}",
                                compact_pattern(&binding.pattern),
                                compact_expression(&binding.initializer)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .collect::<Vec<_>>()
                .join(" then ");
            format!("let {groups} in {}", compact_expression(body))
        }
        Expr::Unary {
            op: UnaryOp::Not,
            operand,
            ..
        } => format!("not {}", compact_expression(operand)),
        Expr::Binary { op, lhs, rhs, .. } => {
            let keyword = match op {
                BinaryOp::And => "and",
                BinaryOp::Or => "or",
            };
            format!(
                "{} {keyword} {}",
                compact_expression(lhs),
                compact_expression(rhs)
            )
        }
        Expr::OperatorCall {
            operator,
            arguments,
            ..
        } => match arguments.as_slice() {
            [operand] => format!("{}{}", operator.symbol, compact_expression(operand)),
            [lhs, rhs] => format!(
                "{}{}{}",
                compact_expression(lhs),
                operator.symbol,
                compact_expression(rhs)
            ),
            _ => format!("{}({})", operator.symbol, compact_expressions(arguments)),
        },
        Expr::Call {
            callee, arguments, ..
        } => format!(
            "{}({})",
            compact_expression(callee),
            compact_expressions(arguments)
        ),
        Expr::Lambda {
            parameters, body, ..
        } => format!(
            "({}): {}",
            parameters
                .iter()
                .map(compact_parameter)
                .collect::<Vec<_>>()
                .join(","),
            compact_expression(body)
        ),
        Expr::RecLambda {
            self_name,
            parameters,
            result_type,
            body,
            ..
        } => format!(
            "rec_fun {self_name}({}) {}: {}",
            parameters
                .iter()
                .map(compact_parameter)
                .collect::<Vec<_>>()
                .join(","),
            compact_type(result_type),
            compact_expression(body)
        ),
        Expr::Return { value, .. } => format!("return {}", compact_expression(value)),
        Expr::Group { inner, .. } => format!("({})", compact_expression(inner)),
        Expr::Conditional {
            condition,
            then_branch,
            else_branch,
            ..
        } => format!(
            "if {} then {} else {} fi",
            compact_expression(condition),
            compact_expression(then_branch),
            compact_expression(else_branch)
        ),
        Expr::Cast { target, body, .. } => {
            format!("{}: {}", compact_type(target), compact_expression(body))
        }
        Expr::Sequence { first, second, .. } => {
            format!(
                "{}; {}",
                compact_expression(first),
                compact_expression(second)
            )
        }
        Expr::While {
            condition, body, ..
        } => {
            let condition = condition
                .as_ref()
                .map(|condition| format!("{} ", compact_expression(condition)))
                .unwrap_or_default();
            format!("while {condition}do {} od", compact_expression(body))
        }
        Expr::For(loop_) => {
            let pattern = loop_
                .pattern
                .as_ref()
                .map(compact_pattern)
                .unwrap_or_default();
            let index = loop_
                .index
                .as_ref()
                .map(|index| format!("@{}", index.value))
                .unwrap_or_default();
            format!(
                "for {pattern}{index} in {} do {} od",
                compact_expression(&loop_.iterable),
                compact_expression(&loop_.body)
            )
        }
        Expr::Break { .. } => "break".to_string(),
        Expr::Case(case) => {
            let branches = case
                .branches
                .iter()
                .map(|branch| {
                    let tag = match &branch.tag {
                        Some(tag) => tag.value.clone(),
                        None => "else".to_string(),
                    };
                    let pattern = branch
                        .pattern
                        .as_ref()
                        .map(compact_pattern)
                        .unwrap_or_default();
                    format!("{tag}{pattern}: {}", compact_expression(&branch.body))
                })
                .collect::<Vec<_>>()
                .join(" | ");
            format!(
                "case {} | {branches} esac",
                compact_expression(&case.subject)
            )
        }
    }
}

fn compact_expressions(expressions: &[Expr]) -> String {
    expressions
        .iter()
        .map(compact_expression)
        .collect::<Vec<_>>()
        .join(",")
}

fn compact_type(type_expr: &TypeExpr) -> String {
    type_expr
        .resolve()
        .display(&crate::types::TypeTable::new())
        .to_string()
}

fn compact_parameter(parameter: &LambdaParam) -> String {
    match parameter {
        LambdaParam::Typed(typed) => {
            format!(
                "{} {}",
                compact_type(&typed.type_expr),
                compact_pattern(&typed.pattern)
            )
        }
        LambdaParam::Tuple { elements, .. } => format!(
            "({})",
            elements
                .iter()
                .map(compact_parameter)
                .collect::<Vec<_>>()
                .join(",")
        ),
    }
}

fn compact_pattern(pattern: &Pattern) -> String {
    match pattern {
        Pattern::Discard { .. } => "()".to_string(),
        Pattern::Name { name, constant, .. } => {
            if *constant {
                format!("!{name}")
            } else {
                name.clone()
            }
        }
        Pattern::Tuple {
            elements, whole, ..
        } => {
            let elements = elements
                .iter()
                .map(compact_pattern)
                .collect::<Vec<_>>()
                .join(",");
            match whole {
                Some(whole) => format!("({elements}): {}", compact_pattern(whole)),
                None => format!("({elements})"),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use malachite::Integer as BigInt;

    fn pattern_shape(pattern: &Pattern) -> String {
        match pattern {
            Pattern::Discard { .. } => "_".to_string(),
            Pattern::Name { name, constant, .. } => {
                if *constant {
                    format!("!{name}")
                } else {
                    name.clone()
                }
            }
            Pattern::Tuple {
                elements, whole, ..
            } => {
                let elements = elements
                    .iter()
                    .map(pattern_shape)
                    .collect::<Vec<_>>()
                    .join(",");
                match whole {
                    Some(whole) => format!("({elements}):{}", pattern_shape(whole)),
                    None => format!("({elements})"),
                }
            }
        }
    }

    fn expression_shape(expression: &Expr) -> String {
        match expression {
            Expr::Integer { value, .. } => value.to_string(),
            Expr::Boolean { value, .. } => value.to_string(),
            Expr::String { value, .. } => format!("\"{value}\""),
            Expr::Tuple { elements, .. } => format!(
                "tuple({})",
                elements
                    .iter()
                    .map(expression_shape)
                    .collect::<Vec<_>>()
                    .join(",")
            ),
            Expr::List { elements, .. } => format!(
                "list({})",
                elements
                    .iter()
                    .map(expression_shape)
                    .collect::<Vec<_>>()
                    .join(",")
            ),
            Expr::Subscription {
                array,
                index,
                reversed,
                ..
            } => format!(
                "sub({},{},{})",
                expression_shape(array),
                expression_shape(index),
                reversed
            ),
            Expr::Slice {
                array,
                lower,
                upper,
                flags,
                ..
            } => format!(
                "slice({},{},{},{}{}{})",
                expression_shape(array),
                expression_shape(lower),
                expression_shape(upper),
                u8::from(flags.reverse_output),
                u8::from(flags.lower_from_end),
                u8::from(flags.upper_from_end)
            ),
            Expr::Identifier { name, .. } => name.clone(),
            Expr::Assignment { name, value, .. } => {
                format!("assign({name},{})", expression_shape(value))
            }
            Expr::Let {
                binding_groups,
                body,
                ..
            } => {
                let groups = binding_groups
                    .iter()
                    .map(|bindings| {
                        bindings
                            .iter()
                            .map(|binding| {
                                format!(
                                    "{}={}",
                                    pattern_shape(&binding.pattern),
                                    expression_shape(&binding.initializer)
                                )
                            })
                            .collect::<Vec<_>>()
                            .join(",")
                    })
                    .collect::<Vec<_>>()
                    .join(";");
                format!("let({groups},{})", expression_shape(body))
            }
            Expr::Unary {
                op: UnaryOp::Not,
                operand,
                ..
            } => {
                format!("not({})", expression_shape(operand))
            }
            Expr::Binary {
                op: BinaryOp::And,
                lhs,
                rhs,
                ..
            } => format!("and({},{})", expression_shape(lhs), expression_shape(rhs)),
            Expr::Binary {
                op: BinaryOp::Or,
                lhs,
                rhs,
                ..
            } => format!("or({},{})", expression_shape(lhs), expression_shape(rhs)),
            Expr::OperatorCall {
                operator,
                arguments,
                ..
            } => format!(
                "{}@{}({})",
                operator.symbol,
                operator.priority,
                arguments
                    .iter()
                    .map(expression_shape)
                    .collect::<Vec<_>>()
                    .join(",")
            ),
            Expr::Group { inner, .. } => format!("group({})", expression_shape(inner)),
            Expr::Conditional {
                condition,
                then_branch,
                else_branch,
                ..
            } => format!(
                "if({};{};{})",
                expression_shape(condition),
                expression_shape(then_branch),
                expression_shape(else_branch)
            ),
            Expr::Cast { target, body, .. } => format!(
                "cast({};{})",
                target.resolve().display(&crate::types::TypeTable::new()),
                expression_shape(body)
            ),
            Expr::Call {
                callee, arguments, ..
            } => format!(
                "call({};{})",
                expression_shape(callee),
                arguments
                    .iter()
                    .map(expression_shape)
                    .collect::<Vec<_>>()
                    .join(",")
            ),
            Expr::Lambda { body, .. } => format!("lambda({})", expression_shape(body)),
            Expr::RecLambda { body, .. } => format!("rec_lambda({})", expression_shape(body)),
            Expr::Return { value, .. } => format!("return({})", expression_shape(value)),
            Expr::Sequence { first, second, .. } => {
                format!(
                    "seq({};{})",
                    expression_shape(first),
                    expression_shape(second)
                )
            }
            Expr::While {
                condition, body, ..
            } => format!(
                "while({};{})",
                condition
                    .as_ref()
                    .map(|condition| expression_shape(condition))
                    .unwrap_or_default(),
                expression_shape(body)
            ),
            Expr::For(loop_) => format!(
                "for({}{};{};{})",
                loop_
                    .pattern
                    .as_ref()
                    .map(pattern_shape)
                    .unwrap_or_default(),
                loop_
                    .index
                    .as_ref()
                    .map(|index| format!("@{}", index.value))
                    .unwrap_or_default(),
                expression_shape(&loop_.iterable),
                expression_shape(&loop_.body)
            ),
            Expr::Break { .. } => "break".to_string(),
            Expr::Case(case) => {
                let branches = case
                    .branches
                    .iter()
                    .map(|branch| {
                        let tag = match &branch.tag {
                            Some(tag) => tag.value.clone(),
                            None => "else".to_string(),
                        };
                        let pattern = branch
                            .pattern
                            .as_ref()
                            .map(pattern_shape)
                            .unwrap_or_default();
                        format!("{tag}{pattern}:{}", expression_shape(&branch.body))
                    })
                    .collect::<Vec<_>>()
                    .join("|");
                format!("case({};{})", expression_shape(&case.subject), branches)
            }
        }
    }

    fn parse_one(source: &str) -> Expr {
        let mut expressions = parse(&SourceText::new(source))
            .expect("formula parses")
            .expressions;
        assert_eq!(expressions.len(), 1);
        expressions.remove(0)
    }

    #[test]
    fn parses_assignment_as_a_right_associative_expression() {
        let expression = parse_one("x := y := 1");
        assert_eq!(expression_shape(&expression), "assign(x,assign(y,1))");
    }

    #[test]
    fn parses_casts_with_the_upstream_type_grammar() {
        assert_eq!(expression_shape(&parse_one("int: 3")), "cast(int;3)");
        // The cast greedily takes the rest of the expression.
        assert_eq!(
            expression_shape(&parse_one("rat: 1 + 2")),
            "cast(rat;+@4(1,2))"
        );
        assert_eq!(
            expression_shape(&parse_one("[int]: []")),
            "cast([int];list())"
        );
        assert_eq!(expression_shape(&parse_one("[*]: []")), "cast([*];list())");
        assert_eq!(
            expression_shape(&parse_one("(int,bool): (1,true)")),
            "cast((int,bool);tuple(1,true))"
        );
        assert_eq!(
            expression_shape(&parse_one("[int,rat]: []")),
            "cast([(int,rat)];list())"
        );
        assert_eq!(
            expression_shape(&parse_one("(int|string): 3")),
            "cast((int|string);3)"
        );
        assert_eq!(
            expression_shape(&parse_one("(void|vec): x")),
            "cast((void|vec);x)"
        );
        assert_eq!(
            expression_shape(&parse_one("(int,int->int): f")),
            "cast((int,int->int);f)"
        );
        assert_eq!(expression_shape(&parse_one("(->): f")), "cast((->);f)");
        assert_eq!(
            expression_shape(&parse_one("((int->bool)->bool): g")),
            "cast(((int->bool)->bool);g)"
        );
        assert_eq!(
            expression_shape(&parse_one("mat: [[1]]")),
            "cast(mat;list(list(1)))"
        );
        // A trailing empty union slot is a void variant.
        assert_eq!(
            expression_shape(&parse_one("(int|): 3")),
            "cast((int|void);3)"
        );
        // `*` keeps working as the multiplication operator.
        assert_eq!(expression_shape(&parse_one("2 * 3")), "*@6(2,3)");
    }

    #[test]
    fn parses_nested_let_with_assignment_in_the_body() {
        let expression = parse_one("let x = 1 in let y = x + 1 in y := y + 1");
        assert_eq!(
            expression_shape(&expression),
            "let(x=1,let(y=+@4(x,1),assign(y,+@4(y,1))))"
        );
    }

    #[test]
    fn parses_tuple_list_and_group_atoms_distinctly() {
        assert_eq!(expression_shape(&parse_one("()")), "tuple()");
        assert_eq!(expression_shape(&parse_one("(1)")), "group(1)");
        assert_eq!(expression_shape(&parse_one("(1,2)")), "tuple(1,2)");
        assert_eq!(expression_shape(&parse_one("[1,2]")), "list(1,2)");
        assert_eq!(expression_shape(&parse_one("[]")), "list()");
    }

    #[test]
    fn parses_forward_reverse_and_chained_subscriptions() {
        assert_eq!(
            expression_shape(&parse_one("[1,2][0]")),
            "sub(list(1,2),0,false)"
        );
        assert_eq!(
            expression_shape(&parse_one("rows~[0][1]")),
            "sub(sub(rows,0,true),1,false)"
        );
    }

    #[test]
    fn parses_and_normalizes_forward_slice_bounds() {
        assert_eq!(
            expression_shape(&parse_one("rows[1:3]")),
            "slice(rows,1,3,000)"
        );
        assert_eq!(
            expression_shape(&parse_one("rows[:3]")),
            "slice(rows,0,3,000)"
        );
        assert_eq!(
            expression_shape(&parse_one("rows[1:]")),
            "slice(rows,1,0,001)"
        );
        assert_eq!(
            expression_shape(&parse_one("rows[:]")),
            "slice(rows,0,0,001)"
        );
    }

    #[test]
    fn distinguishes_parallel_and_sequential_let_groups() {
        assert_eq!(
            expression_shape(&parse_one("let x = 1, y = x in y")),
            "let(x=1,y=x,y)"
        );
        assert_eq!(
            expression_shape(&parse_one("let x = 1 then y = x in y")),
            "let(x=1;y=x,y)"
        );
    }

    #[test]
    fn parses_fixture_program_and_preserves_precedence() {
        let source = SourceText::new(include_str!("../../../tests/fixtures/parse/basic.atlas"));
        let program = parse(&source).expect("fixture parses");
        assert_eq!(program.expressions.len(), 6);
        assert!(
            matches!(program.expressions[0], Expr::Integer { ref value, .. } if value == &BigInt::from(42))
        );
        assert!(matches!(
            program.expressions[1],
            Expr::Boolean { value: true, .. }
        ));
        assert!(
            matches!(program.expressions[2], Expr::String { ref value, .. } if value == "atlas")
        );
        assert_eq!(
            expression_shape(&program.expressions[4]),
            "-@4(*@6(group(+@4(1,2)),3),/@6(4,2))"
        );
        assert!(matches!(
            program.expressions[5],
            Expr::Binary {
                op: BinaryOp::Or,
                ..
            }
        ));
    }

    #[test]
    fn rejects_trailing_expression_token() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/parse/negative_trailing_token.atlas"
        ));
        let error = parse(&source).expect_err("two adjacent expressions are invalid");
        assert_eq!(error.kind, ErrorKind::Syntax);
    }

    #[test]
    fn parses_integer_literals_without_a_machine_word_limit() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/parse/exact_numerics.atlas"
        ));
        let program = parse(&source).expect("arbitrary-precision integer fixture parses");
        assert!(matches!(
            &program.expressions[0],
            Expr::Integer { value, .. }
                if value.to_string() == "1234567890123456789012345678901234567890"
        ));
    }

    #[test]
    fn parses_unary_minus_for_integer_and_grouped_expression() {
        let source = SourceText::new("-123\n-(1 / 2)");
        let program = parse(&source).expect("unary minus source parses");
        assert_eq!(expression_shape(&program.expressions[0]), "-@4(123)");
        assert_eq!(
            expression_shape(&program.expressions[1]),
            "-@4(group(/@6(1,2)))"
        );
    }

    #[test]
    fn reduces_symbolic_formulae_with_atlas_associativity_and_unary_rules() {
        assert_eq!(expression_shape(&parse_one("a-b-c")), "-@4(-@4(a,b),c)");
        assert_eq!(expression_shape(&parse_one("a^b^c")), "^@7(a,^@7(b,c))");
        assert_eq!(expression_shape(&parse_one("-x^2")), "-@4(^@7(x,2))");
        assert_eq!(
            expression_shape(&parse_one("x^-2*y")),
            "*@6(^@7(x,-@4(2)),y)"
        );
    }

    #[test]
    fn maps_symbolic_tokens_to_oracle_priorities() {
        let cases = [
            ("<", 2),
            ("<=", 2),
            (">", 2),
            (">=", 2),
            ("=", 2),
            ("!=", 2),
            ("+", 4),
            ("-", 4),
            ("*", 6),
            ("%", 6),
            ("/", 6),
            ("&", 6),
            ("\\", 6),
            ("\\%", 6),
            ("^", 7),
            ("#", 8),
            ("##", 8),
            ("~", 8),
        ];

        for (symbol, priority) in cases {
            let expression = parse_one(&format!("a{symbol}b"));
            match expression {
                Expr::OperatorCall {
                    operator,
                    arguments,
                    ..
                } => {
                    assert_eq!(operator.symbol, symbol);
                    assert_eq!(operator.priority, priority);
                    assert_eq!(arguments.len(), 2);
                    assert!(operator.span.is_some());
                }
                other => panic!("expected operator call for {symbol}, got {other:?}"),
            }
        }
    }

    #[test]
    fn emits_return_at_and_dot_parser_tokens() {
        let tokens = parser_tokens(&SourceText::new("return @ .")).expect("tokens");
        assert!(matches!(tokens[0].0, ParserToken::Return(_)));
        assert!(matches!(tokens[1].0, ParserToken::At(_)));
        assert!(matches!(tokens[2].0, ParserToken::Dot(_)));
    }

    #[test]
    fn parses_lambda_return_and_selector_forms() {
        assert_eq!(
            expression_shape(&parse_one("(int n): n + 1")),
            "lambda(+@4(n,1))"
        );
        assert_eq!(expression_shape(&parse_one("@: x + 1")), "lambda(+@4(x,1))");
        assert_eq!(
            expression_shape(&parse_one("(int a, rat b): a")),
            "lambda(a)"
        );
        assert_eq!(
            expression_shape(&parse_one("(int n): return n + 1")),
            "lambda(return(+@4(n,1)))"
        );
        // Selectors lower to calls on the receiver, and chain.
        assert_eq!(expression_shape(&parse_one("2.f")), "call(f;2)");
        assert_eq!(expression_shape(&parse_one("().g")), "call(g;tuple())");
        assert_eq!(expression_shape(&parse_one("x.f.g")), "call(g;call(f;x))");
    }

    #[test]
    fn parses_b3a_function_fixture() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/eval/functions_b3.atlas"
        ));
        let program = parse(&source).expect("B3a function fixture parses");
        assert_eq!(program.expressions.len(), 5);
    }

    #[test]
    fn reports_bison_wording_for_an_unexpected_identifier() {
        let error = parse(&SourceText::new("(int n) n + 1")).expect_err("missing lambda colon");
        assert_eq!(error.kind, ErrorKind::Syntax);
        assert_eq!(error.message, "syntax error, unexpected IDENT");
    }

    #[test]
    fn reports_bison_wording_for_an_unexpected_keyword() {
        // Oracle (Atlas 4d3e9449): `syntax error, unexpected IF` — the
        // rec_fun let sugar requires a result type before the body.
        let error = parse(&SourceText::new(
            "let rec_fun f(int n) = if n=0 then 1 else n fi in f(2)",
        ))
        .expect_err("rec_fun sugar without a result type");
        assert_eq!(error.kind, ErrorKind::Syntax);
        assert_eq!(error.message, "syntax error, unexpected IF");
    }

    #[test]
    fn parses_rec_fun_and_let_function_sugar() {
        assert_eq!(
            expression_shape(&parse_one("rec_fun g(int n) int: n * g(n - 1)")),
            "rec_lambda(*@6(n,call(g;-@4(n,1))))"
        );
        // `f(params) = body` desugars to a plain lambda binding.
        assert_eq!(
            expression_shape(&parse_one("let f(int n) = n + 1 in f(2)")),
            "let(f=lambda(+@4(n,1)),call(f;2))"
        );
        assert_eq!(
            expression_shape(&parse_one("let add(int a, int b) = a + b in add(1, 2)")),
            "let(add=lambda(+@4(a,b)),call(add;1,2))"
        );
        assert_eq!(
            expression_shape(&parse_one("let f() = x + 1 in f()")),
            "let(f=lambda(+@4(x,1)),call(f;))"
        );
        // The rec_fun sugar binds the same name as the self reference.
        assert_eq!(
            expression_shape(&parse_one("let rec_fun f(int n) = int: n in f(5)")),
            "let(f=rec_lambda(n),call(f;5))"
        );
    }

    #[test]
    fn parses_b3b_function_fixture() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/eval/functions_b3b.atlas"
        ));
        let program = parse(&source).expect("B3b function fixture parses");
        assert_eq!(program.expressions.len(), 6);
    }

    #[test]
    fn rejects_rec_fun_let_sugar_without_a_result_type() {
        let error = parse(&SourceText::new(
            "let rec_fun f(int n) = if n=0 then 1 else n fi in f(2)",
        ))
        .expect_err("the result type is mandatory in the sugar");
        assert_eq!(error.kind, ErrorKind::Syntax);
    }

    #[test]
    fn parses_binding_patterns() {
        // Tuple destructuring, const, nesting, and whole-value naming.
        assert_eq!(
            expression_shape(&parse_one("let (a, b) = (1, 2) in a + b")),
            "let((a,b)=tuple(1,2),+@4(a,b))"
        );
        assert_eq!(
            expression_shape(&parse_one("let !x = 41 in x + 1")),
            "let(!x=41,+@4(x,1))"
        );
        assert_eq!(
            expression_shape(&parse_one("let (a, (b, c)) = (1, (2, 3)) in a + b + c")),
            "let((a,(b,c))=tuple(1,tuple(2,3)),+@4(+@4(a,b),c))"
        );
        assert_eq!(
            expression_shape(&parse_one("let (a, b): t = (20, 22) in a + b")),
            "let((a,b):t=tuple(20,22),+@4(a,b))"
        );
        // An empty slot discards, `()` throws away, `(p)` groups.
        assert_eq!(
            expression_shape(&parse_one("let (a, , c) = (1, 2, 3) in a")),
            "let((a,_,c)=tuple(1,2,3),a)"
        );
        assert_eq!(
            expression_shape(&parse_one("let () = 1 in 2")),
            "let(_=1,2)"
        );
        assert_eq!(
            expression_shape(&parse_one("let ((a)) = 1 in a")),
            "let(a=1,a)"
        );
    }

    #[test]
    fn parses_parameter_patterns() {
        // `((int a, int b))` is ONE destructuring parameter, while
        // `(int a, int b)` is a two-parameter list.
        let Expr::Lambda { parameters, .. } = parse_one("((int a, int b)): a + b") else {
            panic!("destructuring lambda parses")
        };
        assert_eq!(parameters.len(), 1);
        assert!(matches!(&parameters[0], LambdaParam::Tuple { .. }));
        let Expr::Lambda { parameters, .. } = parse_one("(int a, int b): a + b") else {
            panic!("two-parameter lambda parses")
        };
        assert_eq!(parameters.len(), 2);
        // The anonymous `type .` parameter binds nothing.
        let Expr::Lambda {
            parameters, body, ..
        } = parse_one("(int x, int .): x")
        else {
            panic!("anonymous-parameter lambda parses")
        };
        assert_eq!(parameters.len(), 2);
        assert!(matches!(
            &parameters[1],
            LambdaParam::Typed(typed) if matches!(&typed.pattern, Pattern::Discard { .. })
        ));
        assert_eq!(expression_shape(&body), "x");
    }

    #[test]
    fn parses_b3c_pattern_fixture() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/eval/patterns_b3c.atlas"
        ));
        let program = parse(&source).expect("B3c pattern fixture parses");
        assert_eq!(program.expressions.len(), 5);
    }

    #[test]
    fn parses_unit_and_operator_selectors() {
        // An operator selector lowers to the prefix-shaped operator call.
        assert_eq!(expression_shape(&parse_one("2.-")), "-@4(2)");
        assert_eq!(expression_shape(&parse_one("2.+")), "+@4(2)");
        assert_eq!(expression_shape(&parse_one("2.=")), "=@2(2)");
        assert_eq!(expression_shape(&parse_one("2.*")), "*@6(2)");
        // A unit selector applies the literal as a function.
        assert_eq!(expression_shape(&parse_one("2.3")), "call(3;2)");
        assert_eq!(expression_shape(&parse_one("2.true")), "call(true;2)");
        // Selectors chain like any other postfix suffix.
        assert_eq!(expression_shape(&parse_one("2.-.-")), "-@4(-@4(2))");
        assert_eq!(expression_shape(&parse_one("().f")), "call(f;tuple())");
    }

    #[test]
    fn parses_b3d_selector_fixture() {
        let source = SourceText::new(include_str!(
            "../../../tests/fixtures/eval/selectors_b3d.atlas"
        ));
        let program = parse(&source).expect("B3d selector fixture parses");
        assert_eq!(program.expressions.len(), 3);
    }

    #[test]
    fn parses_loop_and_break_forms() {
        // Sequencing is right-recursive (parser.y:243).
        assert_eq!(
            expression_shape(&parse_one("x := 1; x + 1")),
            "seq(assign(x,1);+@4(x,1))"
        );
        // A while with a condition, and the bare-do constant-true form.
        assert_eq!(
            expression_shape(&parse_one("while x < 5 do x := x + 1 od")),
            "while(<@2(x,5);assign(x,+@4(x,1)))"
        );
        assert_eq!(
            expression_shape(&parse_one("while do break od")),
            "while(;break)"
        );
        // The for-loop pattern reuses the binding grammar; `@` binds the index.
        assert_eq!(
            expression_shape(&parse_one("for i in [1, 2, 3] do i * 2 od")),
            "for(i;list(1,2,3);*@6(i,2))"
        );
        assert_eq!(
            expression_shape(&parse_one("for x@i in [10, 20, 30] do i od")),
            "for(x@i;list(10,20,30);i)"
        );
        assert_eq!(
            expression_shape(&parse_one("for (a, b) in [(1, 2)] do a + b od")),
            "for((a,b);list(tuple(1,2));+@4(a,b))"
        );
        // A begin/end block sequences like any other expression.
        assert_eq!(
            expression_shape(&parse_one("begin 1; 2 end")),
            "group(seq(1;2))"
        );
    }

    #[test]
    fn break_takes_no_value() {
        // The frozen oracle diagnostic for `break x` (loops_b4_rejected):
        // the grammar simply does not continue after `break`.
        let error = parse(&SourceText::new(
            "let x = 0 in while do x := x + 1; if x = 3 then break x fi od",
        ))
        .expect_err("break with a value is a syntax error");
        assert_eq!(error.kind, crate::diagnostic::ErrorKind::Syntax);
        assert_eq!(error.message, "syntax error, unexpected IDENT");
    }

    #[test]
    fn parses_b4_loop_fixture() {
        let source = SourceText::new(include_str!("../../../tests/fixtures/eval/loops_b4.atlas"));
        let program = parse(&source).expect("B4 loop fixture parses");
        assert_eq!(program.expressions.len(), 8);
    }

    #[test]
    fn parses_case_discrimination_forms() {
        // Tag with a collapsed single pattern, and a tag-only branch.
        assert_eq!(
            expression_shape(&parse_one("case u | i(x): x + 1 | s(t): 0 esac")),
            "case(u;ix:+@4(x,1)|st:0)"
        );
        assert_eq!(
            expression_shape(&parse_one("case u | i: 1 | else 2 esac")),
            "case(u;i:1|else:2)"
        );
        // The `()` throw-away and tuple patterns reuse the binding grammar.
        assert_eq!(
            expression_shape(&parse_one("case l | nil(()): 0 | cons((h, t)): h esac")),
            "case(l;nil_:0|cons(h,t):h)"
        );
    }

    fn parse_one_command(source: &str) -> Command {
        let source_text = SourceText::new(source);
        let mut lexer = crate::lex::Lexer::new(&source_text);
        let mut tokens = Vec::new();
        loop {
            let token = lexer.next_token().expect("command lexes");
            if token.kind == crate::lex::TokenKind::Eof {
                break;
            }
            tokens.push(token);
        }
        parse_command(&tokens, &source_text).expect("command parses")
    }

    #[test]
    fn parses_set_type_and_whattype_commands() {
        // The single-name form aliases; struct fields keep their names.
        let command = parse_one_command("set_type Pair = (int x, int y)");
        let Command::SetType {
            definitions,
            tabled,
            ..
        } = command
        else {
            panic!("expected a set_type command")
        };
        assert!(!tabled);
        assert_eq!(definitions.len(), 1);
        assert_eq!(definitions[0].name.value, "Pair");
        let TypeSpec::Struct(fields) = &definitions[0].spec else {
            panic!("expected a struct spec")
        };
        assert_eq!(fields.len(), 2);
        assert!(fields[0]
            .name
            .as_ref()
            .is_some_and(|name| name.value == "x"));
        assert!(fields[1]
            .name
            .as_ref()
            .is_some_and(|name| name.value == "y"));

        // The bracketed form enters the tabled map; a union variant may
        // name the type being defined (recursion).
        let command = parse_one_command("set_type [ IntList = (void nil | (int, IntList) cons) ]");
        let Command::SetType {
            definitions,
            tabled,
            ..
        } = command
        else {
            panic!("expected a set_type command")
        };
        assert!(tabled);
        assert_eq!(definitions.len(), 1);
        let TypeSpec::Union(fields) = &definitions[0].spec else {
            panic!("expected a union spec")
        };
        assert_eq!(fields.len(), 2);
        assert!(matches!(fields[0].type_expr, TypeExpr::Void { .. }));
        let TypeExpr::Tuple { components, .. } = &fields[1].type_expr else {
            panic!("expected a tuple variant")
        };
        assert!(matches!(&components[1], TypeExpr::Named { name, .. } if name == "IntList"));

        let command = parse_one_command("whattype IntList");
        assert!(
            matches!(command, Command::Whattype { target: Expr::Identifier { ref name, .. }, .. } if name == "IntList")
        );
    }
}
