[package]
name = "atlas-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
lalrpop-util = { version = "=0.22.2", default-features = false }
num-bigint = "=0.4.6"
num-rational = "=0.4.2"

[build-dependencies]
lalrpop = { version = "=0.22.2", default-features = false }
